### ISSUE TITLE
Workflow failure: cf2pulumi-release failed

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-aws-native#1004]
## Workflow Failure

[macf2pulumi-releaseter](https://github.com/pulumi/pulumi-aws-native/actions/workflows/cf2pulumi-release.yml) has failed. See the list of failures below:

- https://github.com/pulumi/pulumi-aws-native/actions/runs/5490756309
- https://github.com/pulumi/pulumi-aws-native/actions/runs/5597213534
- https://github.com/pulumi/pulumi-aws-native/actions/runs/5662441303

**Comment by mjeffryes** [comment]
Fixed in #1005

**Comment by mikhailshilkov** [comment]
Thank you! Can we re-trigger the workflow to make sure it works and get a green mark?
