### ISSUE TITLE
annoyance: golang resource tags all different incompatible types

### ISSUE THREAD

**Issue by ploxiln** [pulumi/pulumi-aws-native#1052]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In the pulumi aws-classic golang SDK, every resource New function Args struct has Tags as a `pulumi.StringMapInput` for which you can provide a `pulumi.StringMap`. Example: [rds.InstanceArgs](https://pkg.go.dev/github.com/pulumi/pulumi-aws/sdk/v5@v5.42.0/go/aws/rds#InstanceArgs). You can conveniently use `ToStringMap()` to just pass a concise `map[string]string`, or filling out the `StringMap{ ... }` inline isn't too bad either, just need to `pulumi.String()` any literal values, and you can then mix in any `pulumi.StringOutput` from other resource output attributes etc. You can use common code to manage tags maps for many different resources.

In this new pulumi aws-native golang SDK, every resource New function Args struct has its own tags type. Example: [rds.DbInstanceArgs](https://pkg.go.dev/github.com/pulumi/pulumi-aws-native/sdk/go/aws/rds#DbInstanceArgs). That takes a `DbInstanceTagArrayInput`, the only type satisfying that is a `DbInstanceTagArray`, which is an array of `DbInstanceTagInput`, the only type satisfying that is `DbInstanceTagArgs`. And these are different for every other resource! For example [networkfirewall.FirewallArgs](https://pkg.go.dev/github.com/pulumi/pulumi-aws-native/sdk/go/aws/networkfirewall#FirewallArgs) takes a different incompatible type `FirewallTagArrayInput` ... it follows the exact same pattern, but it's all incompatible types. There are 3 different separate tag type hierarchies in the `networkfirewall` sub-package.

It's quite verbose to fill out literally:

```go
    networkfirewall.FirewallTagArray{
        &networkfirewall.FirewallTagArgs{
            Key: pulumi.String("env"),
            Value: pulumi.String(env),
        },
        &networkfirewall.FirewallTagArgs{
```

Naturally I'd have some helper functions that would fill in or derive common values. I can have some helpers that generate something like a `pulumi.StringMap` with common/derived values, but then for every resource type I need a separate helper function to construct the appropriate type of TagArray with the appropriate type of TagArgs. It's probably possible to make a shared function to do that with reflection, but I'm pretty sure it's not possible to do with Go generics, I've sure tried. (Can't constrain a passed type to satisfy another passed type, and other limitations ...)

Is it really necessary or helpful for all resources to take different incompatible tag array types?

**Comment by iwahbe** [comment]
Hi @ploxiln. Thats definitely annoying. I'm sorry about that. We should be able to fix this, since we use a `pulumi.StringMap` as the tags value.

**Comment by ytimenkov** [comment]
Hope you fix it for other languages as well (Python in particular).
