### ISSUE TITLE
[provider] Implement defaultTags

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-aws-native#107]
The `defaultTags` parameter is not yet implemented. 

**_Please upvote this issue if you need this feature. This helps us to determine roadmap priorities._**

**Comment by alnazaro** [comment]
we must this ability to manage usage/cost reports

**Comment by tusharshahrs** [comment]
#1. Currently, `defaultTags` feature is not available in the aws cloud control api.
#2.  As a workaround, you can use [transformations](https://www.pulumi.com/docs/intro/concepts/resources/options/transformations/) to auto-tag all resources.
#3.  Here is an example of [auto-tagging](https://github.com/joeduffy/aws-tags-example), note, the resources in [taggagble.ts](https://github.com/joeduffy/aws-tags-example/blob/master/autotag-ts/taggable.ts) will need to reflect the aws-native type format `aws-native:cloudfront:Distribution`

**Comment by jkodroff** [comment]
For examples for AWS Classic in multiple languages, see: https://github.com/joeduffy/aws-tags-example

(@tusharshahrs's comment above still applies - the types would need to be translated to the corresponding AWS Native types)

**Comment by pdf** [comment]
The major problem here is that typed tags make transformations pretty much untenable for any strongly-typed languages. #1052 proposes fixing this, though that would be a breaking change.

I suspect that a local implementation of `defaultTags` would benefit greatly from that change.
