### ISSUE TITLE
Creating an existing MemoryDB user does not trigger an error

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws-native#1121]
### What happened?

After debugging the cause of my bug reports (of our app) I found out that the MemoryDB password did not match the one specified by our pulumi stack (using aws-native library). I found out that two stacks using the same pulumi code were both creating the exact same username. However, the stack creating the same username as last did not receive any error, while its settings (at least the password) were ignored.

Turns out that calling `new aws.memorydb.User("memorydb-admin-user", { userName: "admin", /*...otherProps*/ })` does not return an error if the user exists (and just seems to happily assume everything is fine).

### Example

Create two stacks with the code

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws-native";
import * as random from "@pulumi/random";

const memoryDbAdminPassword = new random.RandomPassword("memorydb-admin-password", { length: 32 });

const adminUser = new aws.memorydb.User("memorydb-admin-user", {
  userName: "admin",
  accessString: "on ~* &* +@all",
  authenticationMode: {
    type: "password",
    passwords: [memoryDbAdminPassword.result],
  }
});
```

Notice how only one user (after both stacks are up) are created without any errors.

### Output of `pulumi about`

```
NAME                VERSION
@pulumi/aws-native  0.78.0
@pulumi/pulumi      3.86.0
@pulumi/random      4.14.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @Jimmy89

I tried reproducing this issue but failed so far. Here is my scenario:

1. Copy your program exactly and deploy it once in my stack `dev`.
2. Switch to another stack `dev2` and deploy it again.

The second deployment failed with 

```
error: 1 error occurred:
    	* operation CREATE failed with "AlreadyExists": User admin already exists. (Service: MemoryDb, Status Code: 400, Request ID: a1ef7243-6a8c-4aec-9aa2-f90060cc44bf)
```

Both my stacks are in the same region.

I tried reproducing with a single program with two users:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws-native";
import * as random from "@pulumi/random";

const memoryDbAdminPassword = new random.RandomPassword("memorydb-admin-password", { length: 32 });

const adminUser = new aws.memorydb.User("memorydb-admin-user", {
  userName: "admin",
  accessString: "on ~* &* +@all",
  authenticationMode: {
    type: "password",
    passwords: [memoryDbAdminPassword.result],
  }
});

const adminUser2 = new aws.memorydb.User("memorydb-admin-user2", {
  userName: "admin",
  accessString: "on ~* &* +@all",
  authenticationMode: {
    type: "password",
    passwords: [memoryDbAdminPassword.result],
  }
}, {dependsOn:adminUser });
```

But again, it failed for the second one.

What am I doing differently?

**Comment by mjeffryes** [comment]
Any further information here @Jimmy89 or should we close this issue out for now?
