### ISSUE TITLE
KMS alias does not interpret AWS Cloud Control error correctly, removing other alias!

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws-native#1138]
### What happened?

If you try to create a KMS alias that already exists (accidentally) you get back an error. However, pulumi seems to register that the alias was successful. So when you try to change the alias name and run pulumi again (to create a non-existing alias), pulumi will see this as a replace command, deleting the existing KMS alias that is being used by another KMS key (this is no fun with production data....).

### Example

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws-native";
import * as awsClassic from "@pulumi/aws";

const { partition } = await aws.getPartition();
const { accountId } = await aws.getAccountId();

const key1 = new aws.kms.Key("kms-encrypt-key", {
    name: "testing",
    description: "Testing",
    enabled: true,
    keySpec: "SYMMETRIC_DEFAULT",
    multiRegion: false, // On update set this to true
    pendingWindowInDays: 7,
    keyPolicy: awsClassic.iam.getPolicyDocumentOutput({
        statements: [
            {
                sid: "Enable all User Permissions for root account",
                actions: ["kms:*"],
                resources: ["*"],
                effect: "Allow",
                principals: [{
                    type: "AWS",
                    identifiers: [`arn:${partition}:iam::${accountId}:root`],
                }]
            }
        ],
    }).json,
});

const key2 = new aws.kms.Key("kms-encrypt-key-2", {
    name: "testing",
    description: "Testing",
    enabled: true,
    keySpec: "SYMMETRIC_DEFAULT",
    multiRegion: false, // On update set this to true
    pendingWindowInDays: 7,
    keyPolicy: awsClassic.iam.getPolicyDocumentOutput({
        statements: [
            {
                sid: "Enable all User Permissions for root account",
                actions: ["kms:*"],
                resources: ["*"],
                effect: "Allow",
                principals: [{
                    type: "AWS",
                    identifiers: [`arn:${partition}:iam::${accountId}:root`],
                }]
            }
        ],
    }).json,
});

new aws.kms.Alias("kms-alias-1", {
    aliasName: `alias/testing/1`,
    targetKeyId: key1.arn
});
```

1. Up the pulumi program above.
2. Add a second alias:

```
new aws.kms.Alias("kms-alias-2", {
    aliasName: `alias/testing/1`, // On purpose this is the same alias as alias 1.
    targetKeyId: key2.arn
});
```

3. Up pulumi again, you get an error:

```
  aws-native:kms:Alias (kms-alias-2):
    error: 1 error occurred:
        * operation CREATE failed with "AlreadyExists": An alias with the name arn:aws:kms:REGION:XXXX:alias/testing/1 already exists (Service: Kms, Status Code: 400, Request ID: XXXX)
```

4. Change the `aliasName` of `kms-alias-2` into `aliasName: "alias/testing/2"`.
5. Notice that the alias of key1 is being deleted (because of a replace action of kms-alias-2), which must NOT be the case. Instead it should have been a CREATE action.

### Output of `pulumi about`

```
NAME                VERSION
@pulumi/aws         6.50.0
@pulumi/aws-native  0.81.0
@pulumi/pulumi      3.89.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @Jimmy89, I may be missing something simple, but 

```
name: "testing"
```

doesn't compile for me: there is no `name` property in kms.Key: https://github.com/pulumi/pulumi-aws-native/blob/master/sdk/nodejs/kms/key.ts#L134

If I remove it, the creation fails for me with 

> operation CREATE failed with "InvalidRequest": An ARN in the specified key policy is invalid.

Also, are you specifying the same `name: "testing"` for both keys on purpose?

Any help getting it repro-ed is appreciated.

**Comment by mikhailshilkov** [comment]
I actually fixed my "InvalidRequest" - it was a mistake on my side. I can repro the issue now.

**Comment by mikhailshilkov** [comment]
I logged the sequence of events.

When the second alias is created, the first response we receive is

```
{"ProgressEvent":{"EventTime":1.697926181177E9,"Identifier":"alias/testing/1","Operation":"CREATE","OperationStatus":"IN_PROGRESS","RequestToken":"38aa","TypeName":"AWS::KMS::Alias"}}
```

It looks like the operation has started successfully and we have an Identifier of the (supposedly) new resource. However, the next progress event is

```
{"ProgressEvent":{"ErrorCode":"AlreadyExists","EventTime":1.697926181512E9,"Identifier":"alias/testing/1","Operation":"CREATE","OperationStatus":"FAILED","RequestToken":"38aa","StatusMessage":"An alias with the name arn:aws:kms:eu-central-1:6161385:alias/testing/1 already exists (Service: Kms, Status Code: 400, Request ID: 30b70)","TypeName":"AWS::KMS::Alias"}}
```

Right now, we interpret this sequence as "the resource started to be created but then the process did not get to a success" and we actually record it into Pulumi state as a partially created resource. On the next Pulumi operation we will treat this resource as existing, i.e. we will start managing it, which is wrong.

I will check with AWS folks what the correct semantics are, but it sounds like we are doing it wrong.

**Comment by mariswa** [comment]
AWS team comment: 
----
Create/update/Delete are all async operations, so when you call they will always return IN_PROGRESS status.

Furthermore, we return primary id in cud call when primary id property is not readonly.

So customer should not rely on behavior this to say resource was partially created.\

Furthermore, in CFN we currently check if handler returns AlreadyExists exception on create, and then if the handler returns primary id then it is ignored.

       // In case CREATE handler returns resource model with AlreadyExists exception, override the progress event
        // object to remove it. That's to prevent the physicalResourceId to be recorded, and to prevent CFN to delete
        // the existent resource during the stack rollback
        final boolean isAlreadyExistsExceptionFromCreateHandlerWithModel = (Action.CREATE.equals(request.getAction())
                && OperationStatus.FAILED.equals(progressEvent.getStatus())
                && ALREADY_EXISTS_ERROR_CODE.equals(progressEvent.getErrorCode())
                && nonNull(progressEvent.getResourceModel())
        );
So AlreadyExists exception with primary id returned is treated as resource not created through CFN so it shouldnt be deleted through cfn on rollback.
----

@mikhailshilkov let me know if we need more clarification

**Comment by mikhailshilkov** [comment]
@mariswa Thank you, this is clear. We'll need to adjust the provider behavior.
