### ISSUE TITLE
KMS keyPolicy update on preview wrongly indicates that KMS key arn will change

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws-native#1141]
### What happened?

If you have a multi-zone key (primary key + replica key) and you update the `keyPolicy` attribute of the primary key, the `pulumi preview` wrongly indicates that the `primaryKeyArn` of the replica key will be updated.

The same applies for the KMS key Alias resource, that indicates that the `targetKeyId` will be updated (indicating that the alias moves to another KMS key).

As KMS keys are quite important, you might scare as developer and stop to proceed if Pulumi indicates such wrong information.

### Example

With the following program:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws-native";
import * as awsClassic from "@pulumi/aws";

const { partition } = await awsClassic.getPartition();
const { accountId } = await aws.getAccountId();
const { name: regionName } = await awsClassic.getRegion();

const awsEuWest1Provider = new aws.Provider("euWest1", { ...aws.config, region: "eu-west-1"});
const defaultKeyPolicy = awsClassic.iam.getPolicyDocumentOutput({
    statements: [
        {
            sid: "EnableAllPermissionsForRootAccount",
            actions: ["kms:*"],
            resources: ["*"],
            effect: "Allow",
            principals: [{
                type: "AWS",
                identifiers: [`arn:${partition}:iam::${accountId}:root`],
            }]
        }]
});

const queueKey = new aws.kms.Key("kms-encrypt-queues", {
    name: "testing",
    enabled: true,
    keySpec: "SYMMETRIC_DEFAULT",
    multiRegion: true,
    pendingWindowInDays: 7,
    keyPolicy: defaultKeyPolicy.then(o => o.json),
});

const queueKeyEuWest1Replica = new aws.kms.ReplicaKey("kms-encrypt-queues-replica-eu-west-1", {
    primaryKeyArn: queueKey.arn,
    keyPolicy: defaultKeyPolicy.then(o => o.json),
    enabled: true,
    pendingWindowInDays: 7,
}, { parent: queueKey, provider: awsEuWest1Provider });

const queueKeyAlias = new aws.kms.Alias("kms-encrypt-queues-alias", {
    aliasName: `alias/testing/1`,
    targetKeyId: queueKey.arn
}, { parent: queueKey });

```

1. Run the code above with pulumi up in any region besides `eu-west-1`.
2. Adjust the policy within the variable `defaultKeyPolicy` to any new value.
3. Run `pulumi preview`, get the output below (which is wrong, because the arn of the key remains intact).
4. If you ran `pulumi up -y --skip-preview`, you see that pulumi does not update the `primaryKeyArn` or `targetKeyId`, as updating a policy changes nothing in that regard.

```
     pulumi:pulumi:Stack              your-stack-name              
 ~   ├─ aws-native:kms:Key            kms-encrypt-queues                         update      [diff: ~keyPolicy]
 ~   │  ├─ aws-native:kms:Alias       kms-encrypt-queues-alias                   update      [diff: ~targetKeyId]
 +-  │  └─ aws-native:kms:ReplicaKey  kms-encrypt-queues-replica-eu-west-1       replace     [diff: ~keyPolicy,primaryKeyArn]
```

Solution: only indicate changes in the primary key arn if the key will be/is replaced.

### Output of `pulumi about`

```
NAME                VERSION
@pulumi/aws         6.5.0
@pulumi/aws-native  0.81.0
@pulumi/pulumi      3.89.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
By default, Pulumi engine conservatively expects that any output value can change after a resource is updated. Of course, this is never true for `arn`, but the provider has to explicitly indicate that `arn` won't change.

This is implemented in Azure Native. We need to:
1. Opt into SupportsPreview in Configure: https://github.com/pulumi/pulumi-azure-native/blob/e681f6d004ae21247df5adec72b8740cc81a1915/provider/pkg/provider/provider.go#L216
2. Return stable properties back from Update: https://github.com/pulumi/pulumi-azure-native/blob/e681f6d004ae21247df5adec72b8740cc81a1915/provider/pkg/provider/provider.go#L1168-L1174

We need to do the same in AWS Native.
