### ISSUE TITLE
`GroupResourceQueryTypeArgs` missing but referenced in docs

### ISSUE THREAD

**Issue by Jomik** [pulumi/pulumi-aws-native#1172]
### What happened?

Trying to add a `Type` to a resource group, but unable to create a struct for that argument.
https://github.com/pulumi/pulumi-aws-native/blob/17d2527e901d4e5bead7761bec605262250db0c8/sdk/go/aws/resourcegroups/pulumiEnums.go#L155
It references `GroupResourceQueryTypeArgs` but that does not exist.

### Example

```go
	_, err = resourcegroups.NewGroup(
		ctx,
		"foo",
		&resourcegroups.GroupArgs{
			Name:        pulumi.String("foo"),
			Description: pulumi.String("bar"),
			ResourceQuery: resourcegroups.GroupResourceQueryArgs{
				// Error: undefined
				Type: resourcegroups.GroupResourceQueryTypeArgs{},
			},
		},
	)

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @Jomik

`Type` looks to be an enum, so you should use

```
Type: resourcegroups.GroupResourceQueryTypeTagFilters10,
// or
Type: resourcegroups.GroupResourceQueryTypeCloudformationStack10,
```

I hope this helps.

**Comment by Jomik** [comment]
That makes sense, the comment should probably be updated to reflect that.
Thanks!
