### ISSUE TITLE
Environment variables take precedence over explicit configuration

### ISSUE THREAD

**Issue by midu-git** [pulumi/pulumi-aws-native#1191]
### What happened?

When using the `aws-native` provider setting `profile` explicitly while having the environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` set, the provider ignores the profile configuration and uses the environment variables instead.

### Example

Get a session and set environment, e.g. (zsh)
```shell
STS=(`aws sts assume-role --role-arn 'SOME_ROLE_ARN' --role-session-name 'test' --query '[Credentials.AccessKeyId,Credentials.SecretAccessKey,Credentials.SessionToken]' --duration-seconds ${2:-3600} --output text`)
export AWS_ACCESS_KEY_ID="${STS[1]}"
export AWS_SECRET_ACCESS_KEY="${STS[2]}"
export AWS_SESSION_TOKEN="${STS[3]}"
```
Create your `aws-native` provider using
```typescript
function buildAwsNativeProvider(
    profile: string,
    accountId: string,
    region: awsNative.Region
): awsNative.Provider {
    return new awsNative.Provider(`aws-native-${accountId}-${region}`, {
        profile: profile,
        allowedAccountIds: [accountId],
        region: region,
    });
}
```
Alternatively, set a default provider in `Pulumi.stackname.yaml`
```yaml
config:
  aws:allowedAccountIds:
    - "YOUR_ACCOUNT_ID"
  aws:profile: YOUR_PROFILE
  aws-native:allowedAccountIds:
    - "YOUR_ACCOUNT_ID"
  aws-native:profile: YOUR_PROFILE
```
Creating a resource in this setup results in using the identity provided by the environment variables instead of the one defined by `profile`. It is worth mentioning, that the `aws` provider correctly uses `profile`.

### Output of `pulumi about`

CLI
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.18.2'

Tested with `aws-native` plugins:
```
aws-native  resource  0.86.0
aws-native  resource  0.81.0
```
and `aws` plugins:
```
aws         resource  6.10.0
aws         resource  6.7.0
aws         resource  6.5.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by midu-git** [comment]
Hi @mjeffryes.
Thanks for your feedback. I can't image why someone should assume that environment has higher precedence than  arguments. Usually, the environment is the last in the chain for credential or configuration providers. Looking at the default credential chain provided by the AWS SDK, this is true. For the go cloud SDK, this is true as well. This is not criticism. I just wanted to replay to the point about a possible breaking change.
Moreover, do you test for this behaviour explicitly? If not, this is another argument for not treating this as a breaking change.

This issue made me implement a very hackish GitHub workflow. I need to create resources in different AWS accounts, and thus I need to use different providers. As the action configure-aws-credentials injects the mentioned environment variables, I can't use it out-of-the-box. Therefore, I need to create a `~/.aws/credentials` file with the required content by hand to be able to use the `profile` parameter.
I'd prefer using roles instead, but neither the AWS S3 backend, nor the AWS KMS encryption provider support them. I'm open to suggestions, how this can be solved differently.

**Comment by mjeffryes** [comment]
I don't disagree with you; we should make this change. I was just noting that it's possible that someone is inadvertently depending on the current behavior, so we'll need to call out the change in the release notes.

**Comment by midu-git** [comment]
Hi @mjeffryes. Any rough estimate on when we can expect a solution?

**Comment by rusty-jules** [comment]
Indeed, this behavior is particularly confusing especially when _migrating_ a resource from the `aws` provider to the `aws-native` provider.

**Comment by gio-pcb** [comment]
We are facing a similar issue with our project. In our project we use an AWS provider (lets call it Provider A) to manage resources for our infra. Part of this is managing resources on another completely separated AWS account which we connect to by using a provider that we initialise in our Pulumi code (lets call it Provider B).

Initially we didn't have any issues as both providers were initialised using AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. For security we changed Provider A to use oidc when called by GH Actions. Provider A was working OK but Provider B was failing when called in our pulumi code during the temporary oidc session with error:

```
 pulumi:providers:aws (ProviderB):
      error: rpc error: code = Unknown desc = 2 errors occurred:
      	* unable to validate AWS credentials.
      Details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: XXXXXXXX, api error InvalidClientTokenId: The security token included in the request is invalid
      Make sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`.
```
Here is how we initialise Provider B within our code:

```
  const provider = new aws.Provider("ProviderB", {
    region: "us-east-1",
    accessKey: input.awsMasterAccount.accessKeyId,
    secretKey: input.awsMasterAccount.secretAccessKey,
  });
```

It seems that AWS_SESSION_TOKEN that was set up by Provider A is being passed when initialising provider B. So apart from a precedence issue, it seems there's merging going on between arguments and env variables when initialising the aws provider in such scenario.

Not sure if this would help you @midu-git  but, as a workaround, we are now initialising provider B as below:

```
  const provider = new aws.Provider("ProviderB", {
    region: "us-east-1",
    accessKey: input.awsMasterAccount.accessKeyId,
    secretKey: input.awsMasterAccount.secretAccessKey,
    token: ""
  });
```
