### ISSUE TITLE
Tagging  aws-native Mediaconnect Resources

### ISSUE THREAD

**Issue by sarita-ningappa** [pulumi/pulumi-aws-native#1192]
Hi Team,

I'm currently using aws-native to create mediaconnect flow, since I did not find any method for tagging, I was planning on combining it with boto3 for just tagging. I am getting following error while trying to assign flowarn to a python variable and print.

```
    Calling __str__ on an Output[T] is not supported.
    To get the value of an Output[T] as an Output[str] consider:
    1. o.apply(lambda v: f"prefix{v}suffix")
    See https://www.pulumi.com/docs/concepts/inputs-outputs for more details.
    This function may throw in a future version of Pulumi.
```

Tried to use apply, based on the documentation screenshot attached but getting same error(preview and up).
![Screenshot from 2023-11-27 10-45-25](https://github.com/pulumi/pulumi/assets/87056721/faa80461-77cd-40ec-99b4-33a69129c6c7)
Please help on how to tag these resources.

**Comment by mjeffryes** [comment]
hi @sarita-ningappa; yes, unfortunately the Cloud Control APIs used by AWS native don't implement tagging for mediaconnect resources.

Your workaround should be doable though. Can you share some example code where you're having trouble printing the output with `apply`? You should be able to do something like: `myResource.flowarn.apply(lambda arn: print(f"My ARN: {arn}!")))`

**Comment by sarita-ningappa** [comment]
Hi @mjeffryes 
I do not want to print but to use the ARN. with this, I plan on tagging from boto3.
code snippet is as follows
```
    my_flow = Flow(flow_name,
    name = flow_name, 
    source = final_config
    )
 
    pulumi.export("flowArn", my_flow)
    #my_flow.flow_arn.apply(lambda arn: print(f"My ARN: {arn}!"))

    aws_mag_con=boto3.session.Session()
    mc_client=aws_mag_con.client('mediaconnect',region_name)

    tag_func(mc_client,my_flow.flow_arn,stack)


def tag_func(mediaconnect,tag_arns,stack):
    response = mediaconnect.tag_resource(
        ResourceArn=tag_arns,
        Tags={
            'STACK': stack
        }
)
```
When I'm trying to use the output of Mediaconnect creation as input to a boto3 function, getting the error as follows. 

```
Invalid type for parameter ResourceArn, value: Calling __str__ on an Output[T] is not supported.
    
    To get the value of an Output[T] as an Output[str] consider:
    1. o.apply(lambda v: f"prefix{v}suffix")
    
    See https://www.pulumi.com/docs/concepts/inputs-outputs for more details.
    This function may throw in a future version of Pulumi., type: <class 'pulumi.output.Output'>, valid types: <class 'str'>
```
Please check

**Comment by mjeffryes** [comment]
It should work if you call `tag_func` from inside the apply: 
``` python
    my_flow = Flow(flow_name,
    name = flow_name, 
    source = final_config
    )
 
    pulumi.export("flowArn", my_flow)
    #my_flow.flow_arn.apply(lambda arn: print(f"My ARN: {arn}!"))

    aws_mag_con=boto3.session.Session()
    mc_client=aws_mag_con.client('mediaconnect',region_name)

    my_flow.flow_arn.apply(lambda arn: tag_func(mc_client,arn,stack))


def tag_func(mediaconnect,tag_arns,stack):
    response = mediaconnect.tag_resource(
        ResourceArn=tag_arns,
        Tags={
            'STACK': stack
        }
)
```
