### ISSUE TITLE
aws-native mediaconnect create flow of vpc type

### ISSUE THREAD

**Issue by sarita-ningappa** [pulumi/pulumi-aws-native#1209]
Hi Team, 
I am trying to create mediaconnect flow of type vpc, which requires vpc_interface_name .
i.e vpc_interface should be created to use it in creation of flow.
But vpc_interface creation requires a flow arn which should be present.
Hence this is overlapping and getting error in creating either of them first.
Following is the code snippet

final_config(protocol,description,vpc_interface_name) and source_configuration(vpc_interface_name,vpc details) have the required input parameters.

  ```
  my_flow = Flow(flow_name,
    name = flow_name, # provide a unique name for your flow
    source = final_config
    )

    if source_type.lower()=='vpc':
    # Then, create the Flow VPC Interface
        flow_vpc_interface = mediaconnect.FlowVpcInterface(source_configuration['VpcInterfaceName'], 
        flow_arn=my_flow.flow_arn, 
        name=source_configuration['VpcInterfaceName'],
        role_arn=source_configuration['VpcIamRole'], 
        subnet_id=source_configuration['VpcSubnet'], 
        security_group_ids=[source_configuration['VpcSg']])

```
Please help with the same.

**Comment by sarita-ningappa** [comment]
Hi @mjeffryes ,
can you please check and help with this?

**Comment by mjeffryes** [comment]
I think you have roughly the correct order from what I can gather from the AWS api docs. It looks like you are supposed to
1) create the Flow
2) create the FlowVpcInterface
3) create a [Flow VpcInterfaceAttachment]9https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mediaconnect-flow-vpcinterfaceattachment.html) to connect the Flow to the FlowVpcInterface
