### ISSUE TITLE
EKS NodeGroup update fails if changing the instance size

### ISSUE THREAD

**Issue by tgillitzer** [pulumi/pulumi-aws-native#1244]
### What happened?

Trying to change the instance size on an EKS Node Group.   Expected the node group to be replaced.   Preview showed it as an update.   Went ahead with the update, which failed with the following error:
```CloudControl: UpdateResource, https response error StatusCode: 400, RequestID: 942fbc59-47df-4c7b-9bcf-b961b1b788b6, NotUpdatableException: Invalid patch update: createOnlyProperties [/properties/InstanceTypes] cannot be updated```

### Example

Create an EKS Cluster and a Node Group.

Change the size of the Node Group and run an update.   It will fail with the above error.

It should replace the node group by creating a new one and then deleting the old one.

### Output of `pulumi about`

CLI
Version 3.97.0
Go Version go1.21.5
Go Compiler gc

Plugins
NAME VERSION
aws 6.17.0
aws-native 0.90.0
docker 3.6.1
kubernetes 4.6.1
python unknown

Host
OS Microsoft Windows 11 Pro
Version 10.0.22000 Build 22000
Arch x86_64

This project is written in python: version='3.11.3'

Backend
Name pulumi.com

Dependencies:
NAME VERSION
pip 23.3.1
pulumi-aws 6.17.0
pulumi-aws-native 0.90.0
pulumi-docker 3.6.1
pulumi-kubernetes 4.6.1
setuptools 69.0.2
wheel 0.42.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for reporting this @tgillitzer, looks like we must not be correctly parsing the `CreateOnlyProperties` on this resource. I'll add it to our backlog of schemagen issues.

**Comment by mikhailshilkov** [comment]
@tgillitzer Are you using Python for your Pulumi program?

**Comment by tgillitzer** [comment]
> @tgillitzer Are you using Python for your Pulumi program?
> 
> Likely the same issue as #1318

Yes
