### ISSUE TITLE
Resources stuck in indefinite PENDING status

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-aws-native#1251]
On 2023-12-21, our tests started failing because the Cloud Control APIs began returning PENDING status for some of our resource creation requests. 

We assumed this just indicated a temporary status and added logic to poll for a status change in https://github.com/pulumi/pulumi-aws-native/pull/1228. However, it seems that resources that return the PENDING status do not eventually resolve to a success or failure state, so no our tests simply poll indefinitely until their auth token expires.  

The PENDING state shows up most frequently in our `ParallelTs` test that attempts to create 100 IAM roles in parallel, but other tests are sometimes affected. We have tried:
1) reducing the number of IAM roles created to 30
2) deleting extra IAM roles sitting in the account
3) deleting the old PENDING requests on the account

We've also tried the tests on different AWS accounts and seen the same behavior. Given the above, we suspect that this is an issue with CloudControl or that there is some further action the API is expecting the client to take to advance the PENDING tasks.

This issue has some urgency as it has been blocking schema updates on this provider

**Comment by mariswa** [comment]
@mjeffryes is it a specific resource which has status PENDING or randomly? Could you attach the sample code for a resource which marked as PENDING to the ticket?

**Comment by mjeffryes** [comment]
Here's a link to the pulumi example that triggers the problem: 
https://github.com/pulumi/pulumi-aws-native/blob/master/examples/parallel-ts/index.ts

The method where we poll for status updates in our provider is here: https://github.com/pulumi/pulumi-aws-native/blob/5e782c3fa42ed12c472551274fba2129acedfe05/provider/pkg/provider/provider.go#L1135



For examples of pending resources it's probably clearest to look at the logs from one of the earlier runs where we simply failed on PENDING status: 

https://github.com/pulumi/pulumi-aws-native/actions/runs/7177001394/job/19542973229

We see PENDING responses for `aws-native:logs:LogGroup` and `aws-native:sqs:Queue (fifo-queue)` resources in addition to the PENDING `aws-native:iam:Role` resources. Obviously, the simple fact that resources are PENDING is not a problem if these resources were to resolve eventually. The problem does seem to be exacerbated by the number of resources being created in parallel. 

It should be relatively easy to reproduce the problem with that example code, especially if you crank up the number of roles created; I just ran our test suite a few minutes ago (https://github.com/pulumi/pulumi-aws-native/actions/runs/7382299954/job/20106379616?pr=1250) and got an SQS queue stuck: 
```
 aws --profile pulumi-ci cloudcontrol list-resource-requests --resource-request-status-filter "OperationStatuses=PENDING"
{
    "ResourceRequestStatusSummaries": [
        {
            "TypeName": "AWS::SQS::Queue",
            "RequestToken": "76655714-9fd7-40a8-b52c-e103af3d078f",
            "OperationStatus": "PENDING",
            "EventTime": "2024-01-02T13:44:08.382000-08:00"
        }
    ]
}
```

**Comment by shrsrivz** [comment]
Can you confirm if the same tests were working before 2023-12-21 and when was the last time these tests passed?

**Comment by mjeffryes** [comment]
yes these tests were passing prior to 2023-12-21 and had been running for some time prior; the last successful run of these tests was at 2023-12-09T05:15:35Z https://github.com/pulumi/pulumi-aws-native/actions/runs/7149172628/job/19471220798

**Comment by EronWright** [comment]
The issue appears to be resolved, see successful job run: https://github.com/pulumi/pulumi-aws-native/actions/runs/7456738228
