### ISSUE TITLE
Dynamodb: on failure (duplicate name) pulumi throws away existing database

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws-native#1263]
### What happened?

When creating a second DynamoDB table, I forgot to change the name of the second table to any other name that the first table (copy and paste lines of code without changing name). Pulumi brought back the AWS error that a table already existed with the same name. I changed the name of the second table and upped again. However, to my surprise, it 'replaces' the second table by removing the first table. Somehow pulumi did not detect the AWS error and thought the second DynamoDB table was created (with the same name).

Luckily, this was on my test environment...

### Example

Javascript snippet

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws-native";

const dynamodbTableHashKey = "PK";
const dynamodbTableRangeKey = "SK";
const dynamodbTableName1 = "table1";
const dynamodbTableName2 = "table1";

const table1 = new aws.dynamodb.Table(`dynamodb-1`, {
  attributeDefinitions: [
    {
      attributeName: dynamodbTableHashKey,
      attributeType: "S",
    },
    {
      attributeName: dynamodbTableRangeKey,
      attributeType: "S",
    },
  ],
  deletionProtectionEnabled: false,
  keySchema: [
    {
      attributeName: dynamodbTableHashKey,
      keyType: "HASH",
    },
    {
      attributeName: dynamodbTableRangeKey,
      keyType: "RANGE",
    },
  ],
  tableName: dynamodbTableName1,
  billingMode: "PAY_PER_REQUEST",
  timeToLiveSpecification: {
    attributeName: "TTL",
    enabled: false,
  },
}, { replaceOnChanges: ["tableName"], deleteBeforeReplace: true, });


// const table2 = new aws.dynamodb.Table("dynamodb-2", {
//   attributeDefinitions: [
//     {
//       attributeName: dynamodbTableHashKey,
//       attributeType: "S",
//     },
//     {
//       attributeName: dynamodbTableRangeKey,
//       attributeType: "S",
//     },
//   ],
//   deletionProtectionEnabled: false,
//   keySchema: [
//     {
//       attributeName: dynamodbTableHashKey,
//       keyType: "HASH",
//     },
//     {
//       attributeName: dynamodbTableRangeKey,
//       keyType: "RANGE",
//     },
//   ],
//   tableName: dynamodbTableName2,
//   billingMode: "PAY_PER_REQUEST",
//   timeToLiveSpecification: {
//     attributeName: "TTL",
//     enabled: false,
//   },
// }, { replaceOnChanges: ["tableName"], deleteBeforeReplace: true });
```

1. Up this snippet.
2. Remove comments at the end of the snippet, so a second table is created.
3. Get the error:

```
 aws-native:dynamodb:Table (dynamodb-2):
    error: 1 error occurred:
        * operation CREATE failed with "AlreadyExists": Resource of type 'AWS::DynamoDB::Table' with identifier 'table1' already exists.
```

4. Rename the table name within variable `dynamodbTableName2` to `table2`.
5. Run pulumi up, see that it will execute a replace statement where it deletes table1, which it should NOT do.

Clearly at step 3 pulumi should detect an error preventing the creation of the table.

### Output of `pulumi about`

```
NAME                VERSION
@pulumi/aws-native  0.92.0
@pulumi/pulumi      3.100.0
@pulumi/random      4.15.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for the bug report @Jimmy89. Sounds like the state is getting updated even though the update failed. As a workaround, a `pulummi refresh` after an error like would probably get you back in a safe place, but agree that this shouldn't happen in the first place.
