### ISSUE TITLE
Error on changing `aws_native.ecs.TaskDefinition` container definitions

### ISSUE THREAD

**Issue by ghferrari** [pulumi/pulumi-aws-native#1318]
### What happened?

I'm using `aws_native` via Python. I have defined an `aws_native.ecs.TaskDefinition` resource. It includes a single `container_definition` which specifies a docker image. Deploying the resource the first time is fine. But when I attempt to update the `image` reference in the `container_definition` it fails with this error:
```
error: operation error CloudControl: UpdateResource, https response error StatusCode: 400, RequestID: <redacted>, NotUpdatableException: Invalid patch update: createOnlyProperties [/properties/ContainerDefinitions] cannot be updated
```
It appears that pulumi is attempting to _update_ the TaskDefinition in place, which is confirmed by running `pulumi preview`. Instead, I think pulumi should be attempting to _replace_ the TaskDefinition, since the cloudformation docs specify that updating the `container_definition` will require replacement.

### Example

Define an `aws_native.ecs.TaskDefinition` resource with a container definition referencing a particular image:
```
api_server_task = aws_native.ecs.TaskDefinition(
    "APIServerTask",
    cpu="256",
    execution_role_arn=ecs_task_execution_role.arn,
    family='api_server',
    memory='1024',
    network_mode='awsvpc',
    requires_compatibilities=['FARGATE'],
    container_definitions=[
        aws_native.ecs.TaskDefinitionContainerDefinitionArgs(
            image=my_first_image,
            name=api_server_container_name,
            essential=True,
            port_mappings=[
                aws_native.ecs.TaskDefinitionPortMappingArgs(
                container_port=80
                )
            ],
    ]
)
```

After deploying the above, update the `image` to point to a new image and attempt to redeploy.

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.103.1
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.19.0
aws-native  0.95.0
python      unknown

Host     
OS       debian
Version  trixie/sid
Arch     x86_64

This project is written in python: executable='<redacted>/python3' version='3.11.7'

Current Stack: dappel/agileorca-ecs-services/testing

TYPE                               URN
<redacted>

Found no pending operations associated with testing

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ghferrari
User           ghferrari
Organizations  ghferrari, dappel
Token type     personal

Dependencies:
NAME               VERSION
pip                23.3.2
pulumi_aws         6.19.0
pulumi-aws-native  0.95.0
setuptools         69.0.3
wheel              0.42.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for reporting this @ghferrari; looks like this is a case where we're not handling the createOnlyProperties field in the schema correctly and sending one of these properties on update.

In the meantime, since the correct behavior is to destroy and replace the resource, you can try removing from the program, running an update, adding the resource back to the program with new values, and running `pulumi up` again.

**Comment by rveitch** [comment]
Experiencing this issue as well on `v3.104.2`, it is a bit of a blocker.

<img width="1838" alt="image" src="https://github.com/pulumi/pulumi-aws-native/assets/12876929/1c36315c-cc9b-4e3a-b3b7-797131ead0f3">

**Comment by ghferrari** [comment]
@mjeffryes Thanks for the `replaceOnChanges` hint - that's a neat workaround.

**Comment by ghferrari** [comment]
@rveitch That looks like a different error message to me. I read that error message as telling you that in your first container definition you have included the property `credentialSpecs`, but there is no such property.

**Comment by mikhailshilkov** [comment]
This appears to be a Python-only problem, tracked it down to https://github.com/pulumi/pulumi/issues/15665, a fix is incoming

**Comment by corymhall** [comment]
Reopening this since the original issue of not handling the createOnlyProperties field in the schema is still an issue.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/2191

**Comment by corymhall** [comment]
> Reopening this since the original issue of not handling the createOnlyProperties field in the schema is still an issue.

Actually it looks like I was wrong and this was due to a different issue in pulumi-cdk.
