### ISSUE TITLE
Unable to tag resourceexplorer2 resources

### ISSUE THREAD

**Issue by spock-abadai** [pulumi/pulumi-aws-native#1368]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When creating an `Index` or `View` resource in `resourceexplorer2` in typescript, the `tags` property has a type that is empty (e.g. `IndexTagMapArgs`). Any attempt to provide tags results in a typescript compilation error. This is unlike other aws-native resources (such as ec2 instances, lambda functions, s3 buckets) where the tags argument has a type that is a list of key/value pairs, and also unlike the equivalent resources in the AWS classic provider where the `tags` property is a record-like object.

**Comment by mjeffryes** [comment]
Hi @spock-abadai; we've actually been working on fixing tags recently so you'll see a reasonable type (https://github.com/pulumi/pulumi-aws-native/blob/8a585ead57ae93d385cf1691b7693d6f4a1133c2/sdk/nodejs/resourceexplorer2/view.ts#L43) in the next release (which will come out later this week).
