### ISSUE TITLE
Kinesis Firehose ExtendedS3Configuration support for FileExtension

### ISSUE THREAD

**Issue by dygfloyd** [pulumi/pulumi-aws-native#1372]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
[Kinesis Firehose ExtendedS3Configuration](https://www.pulumi.com/registry/packages/aws/api-docs/kinesis/firehosedeliverystream/#extended-s3-destination-with-dynamic-partitioning) current does not support the optional FileExtension property. This property is described in the [AWS Destination Settings documentation](https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-s3). This causes issues when you are trying to import files in S3 into other systems that require specific file extensions. For example, Datadog log rehydration only supports files with the extension `.json.gz`.

**Note:** This issue was also raised in the [Pulumi AWS repo](https://github.com/pulumi/pulumi-aws/issues/3479).

**Comment by mjeffryes** [comment]
Sorry @dygfloyd, this provider is just a projection of the AWS CloudControl API and  it looks like the Cloudformation schema for Kinesis Firehose doesn't include the file extension parameter. You can file an upstream issue with the cloud control team on https://github.com/aws-cloudformation/cloudformation-coverage-roadmap and as soon as they add it we'll pick it up in this provider.

**Comment by mikhailshilkov** [comment]
FileExtension has now been added 
<img width="732" alt="image" src="https://github.com/pulumi/pulumi-aws-native/assets/1454008/0327db7c-38d1-4164-adfd-ca3ec00a3fd5">
