### ISSUE TITLE
@pulumi/pulumi  v3.109.0 breaks Node.js provider SDK TypeScript compilation

### ISSUE THREAD

**Issue by Suqu13** [pulumi/pulumi-aws-native#1401]
### What happened?

Getting the following TSC errors compiling `@pulumi/aws-native: 0.98.0` with `@pulumi/pulumi: 3.109.0"`. See the example.

I found a similar issue within the `@pulumi/pulumi` repository: https://github.com/pulumi/pulumi/issues/15556. I believe that this problem may occur for the `3.108.0` version as well. I tested it with `3.107.0` and it looks fine.

### Example

`package.json` dependencies:
```json
    "dependencies": {
        "@pulumi/aws-native": "0.98.0",
        "@pulumi/pulumi": "3.109.0"
    },
```

`tsc` command output:
```bash
> tsc

node_modules/@types/glob/index.d.ts:26:42 - error TS2694: Namespace '"/Users/jgarstka/Desktop/NetworkedAssets/imoa/ci-cd/node_modules/minimatch/dist/cjs/index"' has no exported member 'IOptions'.

26     interface IOptions extends minimatch.IOptions {
                                            ~~~~~~~~

node_modules/@types/glob/index.d.ts:72:30 - error TS2724: '"/Users/jgarstka/Desktop/NetworkedAssets/imoa/ci-cd/node_modules/minimatch/dist/cjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?

72         minimatch: minimatch.IMinimatch;
                                ~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@types/glob/index.d.ts:26
```

### Output of `pulumi about`

```bash
❯ pulumi about
CLI          
Version           3.102.0
Go Version     go1.21.6
Go Compiler  gc

Plugins
NAME          VERSION
aws              5.43.0
aws-native  0.98.0
nodejs         unknown
tls                4.11.1

Host     
OS          darwin
Version  14.4
Arch       arm64

This project is written in nodejs: executable='/Users/jgarstka/.nvm/versions/node/v20.5.1/bin/node' version='v20.5.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by bednarek-p** [comment]
Experiencing the same issue. It's a bit of a blocker.

**Comment by mjeffryes** [comment]
So the problem here is that pu/pu v3.108.0 and above introduces a dependency on `glob` v8.0.1 that conflicts with the older `@types/glob` which was imported (unnecessarily as it turns out) by the aws-native SDK. We've actually already removed this on master (https://github.com/pulumi/pulumi-aws-native/pull/1384), so the next release of aws-native will not have this problem.
