### ISSUE TITLE
Python TypeError from sso.get_permission_set with inline policy

### ISSUE THREAD

**Issue by JeffLandis** [pulumi/pulumi-aws-native#1403]
### What happened?

I was trying to get an existing IAM Identity Center (SSO) permission set using python. The permission set contained an inline policy. I was expecting to get an AwaitableGetPermissionSetResult/GetPermissionSetResult back from the get_permission_set call. Instead I got a "TypeError: Expected argument 'inline_policy' to be a dict"

```
    File "/home/jeff/python/pulumi-py/lib/python3.11/site-packages/pulumi_aws_native/sso/get_permission_set.py", line 31, in __init__
    raise TypeError("Expected argument 'inline_policy' to be a dict")
    TypeError: Expected argument 'inline_policy' to be a dict
```
[TypeError.txt](https://github.com/pulumi/pulumi-aws-native/files/14565235/TypeError.txt)

### Example

Using pulumi preview or up get an existing SSO permission set that has an inline policy defined.

```
    from pulumi_aws_native import sso
                                              
    instance_arn = 'arn:aws:sso:::instance/ssoins-xxxxxxxxxxxxxxxx'
    permission_set_arn = 'arn:aws:sso:::permissionSet/ssoins-xxxxxxxxxxxxxxxx/ps-xxxxxxxxxxxxxxxx'

    sso.get_permission_set(instance_arn, permission_set_arn)
```

### Output of `pulumi about`

CLI
Version      3.108.1
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.25.0
aws-native  0.98.0
python      unknown
random      4.16.0

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/home/jeff/python/pulumi-py/bin/python3' version='3.11.7'

Current Stack: organization/aws-management/iam-identity-center

TYPE                          URN
pulumi:providers:aws          urn:pulumi:iam-identity-center::aws-management::pulumi:providers:aws::default
pulumi:pulumi:Stack           urn:pulumi:iam-identity-center::aws-management::pulumi:pulumi:Stack::aws-management-iam-identity-center
pulumi:providers:aws-native   urn:pulumi:iam-identity-center::aws-management::pulumi:providers:aws-native::default_0_98_0

Found no pending operations associated with iam-identity-center

Backend
Name           PC-DESKTOP
URL            s3://pulumi-apse1-xxxxxxxxxxxxxxxx
User           jeff
Organizations
Token type     personal

Dependencies:
NAME               VERSION
boto3              1.34.55
pip                24.0
pulumi_aws         6.25.0
pulumi_aws_native  0.98.0
pulumi_random      4.16.0
ruamel.yaml        0.18.6
setuptools         69.0.3
wheel              0.42.0

### Additional context

GetPermissionSetResult class is expecting "inline_policy" to be a "dict".

sdk\python\pulumi_aws_native\sso\get_permission_set.py
```
30        if inline_policy and not isinstance(inline_policy, dict):
31           raise TypeError("Expected argument 'inline_policy' to be a dict")
32       pulumi.set(__self__, "inline_policy", inline_policy)
```
The type in the schema is [ "object", "string" ].
```
    "InlinePolicy" : {
      "description" : "The inline policy to put in permission set.",
      "type" : [ "object", "string" ]
    },
```

[AWS CloudFormation User Guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-permissionset.html)
InlinePolicy
The inline policy that is attached to the permission set.
Type: Json

I changed line 30 in get_permission_set.py to "str" for testing and it worked as expected. I did indeed get JSON as a string for "inline_policy".
```
'inline_policy': '{"Statement":[{"Action":["iam:PassRole","iam:ListRoles","iam:GetRole"],"Effect":"Allow","Resource":"arn:aws:iam::*:role/MU.ECS.*","Sid":"AllowPassRole"}],"Version":"2012-10-17"}'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for the bug report @JeffLandis. I think the type error here came from us missing support for properties with multiple types. (`inline_policy` is declared as `["object", "string"]` in the CF schema.) The good news is that we have fixed support for these kinds of types in https://github.com/pulumi/pulumi-aws-native/pull/1383. You should see the fix in the next release.

**Comment by JeffLandis** [comment]
Excellent, thanks @mjeffryes. I thought this might be the case since I was able to set inline_policy with a dictionary.
