### ISSUE TITLE
resiliencehub.ResiliencyPolicy does not apply auto-naming

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-aws-native#1430]
### What happened?

The code snippet below fails with `policy_name` is required. I expect `policy_name` to be optional and to be calculated from the resource name by default (auto-naming).

### Example

```py
policy = resiliencehub.ResiliencyPolicy(
  "policy",
  tier=resiliencehub.ResiliencyPolicyTier.NON_CRITICAL,
  policy={
    'Software': resiliencehub.ResiliencyPolicyFailurePolicyArgs(
      rto_in_secs=10,
      rpo_in_secs=10,
    ),
    'Hardware': resiliencehub.ResiliencyPolicyFailurePolicyArgs(
      rto_in_secs=10,
      rpo_in_secs=10,
    ),
    'AZ': resiliencehub.ResiliencyPolicyFailurePolicyArgs(
      rto_in_secs=10,
      rpo_in_secs=10,
    ),
    'Region': resiliencehub.ResiliencyPolicyFailurePolicyArgs(
      rto_in_secs=10,
      rpo_in_secs=10,
    ),
  },
  tags={"localTag": "localTagValue"},
)
```

### Output of `pulumi about`

aws-native version 0.99.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
There appears to be nothing that indicates that property is special. Can’t remember how we infer it - but I’m pretty sure it has to be at least in `createOnlyProperties` if not the `primaryIdentifier`.

https://github.com/pulumi/pulumi-aws-native/blob/45a182d8cc5c4a8852479c0f3ec91825ee885287/aws-cloudformation-schema/aws-resiliencehub-resiliencypolicy.json#L86-L88

This might require an upstream change to the specification.
