### ISSUE TITLE
Unable to get oidc_provider details if deploying eks cluster from scratch using eks.cluster function 

### ISSUE THREAD

**Issue by abhishekmahajan0709222** [pulumi/pulumi-aws-native#1522]
### What happened?

Unable to get oidc_provider details if deploying eks cluster from scratch using eks.cluster function 

I am trying to use oidc_url for another function

### Example

oidc_url = cluster.identity.apply(lambda identity: identity.oidc.issuer)

not working

### Output of `pulumi about`

pulumi about
CLI          
Version      3.113.3
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.32.0
resource  awsx        2.9.0
resource  docker      4.5.3
resource  eks         2.3.0
resource  kubernetes  4.11.0
language  python      unknown

Host     
OS       darwin
Version  13.6.1
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.8.0'

Dependencies:
NAME         VERSION
boto3        1.34.95
kubernetes   29.0.0
pip          24.0
pulumi_awsx  2.9.0
pulumi_eks   2.3.0
ruamel.yaml  0.18.6
setuptools   41.2.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thank you for reporting the issue. Could you please include a full minimal Pulumi program source with expected vs actual behavior? Much appreciated.
