### ISSUE TITLE
Creating an events.Rule with targets seems impossible to do?

### ISSUE THREAD

**Issue by thelegendtubaguy** [pulumi/pulumi-aws-native#1529]
### What happened?

I tried switching over to this provider as the AWS Terraform provider does not have AppSync target support yet.  It doesn't look like I can create an `aws_native.events.Target` with this yet, so have to do that through the `Rule` resource.  But the `RuleTarget` type requires an `arn` and an `id`, neither of which I have because I'm trying to create it :)

### Example

Typescript will complain that you have not provided an `arn` and `id` for your target.
```typescript
const pushEventAppSyncRule = new aws_native.events.Rule('PushEventAppSyncRule', {
    name: `${$app.stage}-push-event`,
    eventBusName: bus.name,
    eventPattern: JSON.stringify({
        'detail-type': ['ServiceMessage'],
    }),
    roleArn: eventBridgeRuleTargetAppSyncRole.arn,
    targets: [
        {
            appSyncParameters: { graphQlOperation: 'pushEvent' },
        },
    ],
})
```

### Output of `pulumi about`

```
@pulumi/aws-native 0.105.0
```

I'm using pulumi via SST Ion, so I don't have exactly what you're asking for.  Hopefully library version is enough.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
@thelegendtubaguy the `id` should be a unique identifier that you generate to identify the target, it does not need to reference another resource. The `arn` is the `arn` of the target resource, which in your case I believe is the `AppSync` target.

Let me know if this helps or if I misunderstood the issue.
