### ISSUE TITLE
Missing `eks.getClusterAuth` and `ec2. getManagedPrefixList`  from `pulumi-aws`

### ISSUE THREAD

**Issue by izaakschroeder** [pulumi/pulumi-aws-native#1532]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Per title, [eks.getClusterAuth](https://www.pulumi.com/registry/packages/aws/api-docs/eks/getclusterauth/) and [ec2. getManagedPrefixList](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/getmanagedprefixlist/) are missing? from this provider. I could be missing the fact there is now another way to do this… but nothing so far that I know of. I've been trying to move some K8S provisioning fully to `pulumi-aws-native` and this is the final missing piece!

**Comment by corymhall** [comment]
@izaakschroeder you are correct, these functions do not exist in the `aws-native` provider. The `aws-native` provider maps directly to the AWS Cloud Control API which does not contain this functionality. There are some features that are supported by `aws-native` and not supported by `pulumi-aws`, and there are some features supported by `pulumi-aws` and not supported by `aws-native` so we recommend using a combination of both providers as needed.

**Comment by izaakschroeder** [comment]
Thanks @corymhall 😄 sorry, I'm sure you get this kind of question a lot. Is there a spot I can go to so that I can check the Cloud Control API before posting here? And is there a spot to file a similar "bug" on the Amazon side? If they want that…

Thanks again for your responsiveness!

**Comment by mjeffryes** [comment]
Hi @izaakschroeder you can file issues against cloudformation on https://github.com/aws-cloudformation/cloudformation-coverage-roadmap. The source of truth for what's in the schemas is at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html, but generally we have the latest version unpacked at https://github.com/pulumi/pulumi-aws-native/tree/master/aws-cloudformation-schema which makes it a little easier to browse.
