### ISSUE TITLE
Cannot update a Cost Category with no split charge rules

### ISSUE THREAD

**Issue by tvanbaak** [pulumi/pulumi-aws-native#1563]
### What happened?

Attempting to update a Cost Category (`AWS::CE::CostCategory`) that has no split charge rules will fail with an error `Value '[]' at 'splitChargeRules' failed to satisfy constraint: Member must have length greater than or equal to 1`.

### Example

`package.json`

```json
{
  "name": "costcategory",
  "devDependencies": {
    "@types/node": "^10.17.60"
  },
  "dependencies": {
    "@pulumi/aws-native": "~0.103.0"
  }
}
```

`Pulumi.main.yaml`

```yaml
config:
  aws-native:region: us-east-1
```

`index.ts`

```ts
import { ce } from "@pulumi/aws-native";

const platformComponent = new ce.CostCategory("testCategory", {
    name: "Pulumi Test Category",
    ruleVersion: ce.CostCategoryRuleVersion.CostCategoryExpressionV1,
    rules: `[{
        "Value": "Taxes",
        "Rule": {
            "Dimensions": {
                "Key": "RECORD_TYPE",
                "Values": ["Tax"],
                "MatchOptions": ["EQUALS"]
            }
        },
        "Type": "REGULAR"
    }]`,
    splitChargeRules: `[]`, // see note below
});
```

Attempting to `pulumi up` this stack will fail with this error:

```
error: creating resource: creating resource (await): operation CREATE failed with "GeneralServiceException": 1 validation error detected: Value '[]' at 'splitChargeRules' failed to satisfy constraint: Member must have length greater than or equal to 1 (Service: CostExplorer, Status Code: 400, Request ID: 0cc2fb11-f5cb-4228-9448-2b9c4c385082)
```

This error goes away if you delete the `splitChargeRules` property. However, if you then make a change to the rule string (e.g. change `"Taxes"` to `"Death and Taxes"`) and `pulumi up` again, the update will fail with the same error:

```
error: operation UPDATE failed with "GeneralServiceException": 1 validation error detected: Value '[]' at 'splitChargeRules' failed to satisfy constraint: Member must have length greater than or equal to 1 (Service: CostExplorer, Status Code: 400, Request ID: f22c2201-949a-4249-aa13-4646174ed12a)
```

Based on my experimentation with the Cloud Control API, the problem is that having no split charge rules is represented by the absence of `splitChargeRules` rather than the property value being an empty array. For example, on a cost category with a split charge rule, this Cloud Control update:

```bash
aws cloudcontrol update-resource \
  --type-name AWS::CE::CostCategory \
  --identifier arn:aws:ce::xxxxxxxxxxxx:costcategory/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx \
  --patch-document '[{"op":"replace", "path":"SplitChargeRules", "value":"[]"}]'
```

fails with the "Member must have length greater than or equal to 1" message. However, the patch document `'[{"op":"remove", "path":"SplitChargeRules"}]'` succeeds and the split charge rule is removed. Moreover, the removal is idempotent and works even if there weren't any split charge rules to begin with.

I haven't tried to check what patch document is actually being sent to Cloud Control yet, but I suspect that it has a `op:replace, path:SplitChargeRules, value:[]` patch in it. That patch should be `op:remove, path:SplitChargeRules` instead.

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.112.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
aws-native  0.103.0
nodejs      unknown

Host     
OS       debian
Version  bullseye/sid
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v20.14.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/tvanbaak
User           tvanbaak
Organizations  tvanbaak, Ozette
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/aws-native  0.103.0
@types/node         10.17.60

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

I tried out the AWS Native plugin because the classic AWS plugin doesn't seem to have a concept of the rule order. When I imported an existing rule, the order was apparently random, not the rule order in AWS Console. Changing rule ordering didn't create any diff either. In my use case, the categorization of costs depends on the order in which the rules are evaluated and the categorization would be incorrect if the rules were shuffled.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tvanbaak** [comment]
I apologize, I think this may actually be a bug with Cloud Control API. `pulumi up --non-interactive --yes -v=10 --logflow` seems to have the right patch document. The POST to cloudcontrolapi has this body:

```json
{"ClientToken":"0689f858-f3b4-49fa-b7ad-faa00421abdf","Identifier":"arn:aws:ce::xxxxxxxxxxxx:costcategory/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","PatchDocument":"[{\"op\":\"replace\",\"path\":\"/Rules\",\"value\":\"[{\\n        \\\"Value\\\": \\\"Death and Taxes\\\",\\n        \\\"Rule\\\": {\\n            \\\"Dimensions\\\": {\\n                \\\"Key\\\": \\\"RECORD_TYPE\\\",\\n                \\\"Values\\\": [\\\"Tax\\\"],\\n                \\\"MatchOptions\\\": [\\\"EQUALS\\\"]\\n            }\\n        },\\n        \\\"Type\\\": \\\"REGULAR\\\"\\n    }]\"}]","TypeName":"AWS::CE::CostCategory"}
```

but then the response is this:

```json
{"ProgressEvent":{"EventTime":1.717108200477E9,"Identifier":"arn:aws:ce::xxxxxxxxxxxx:costcategory/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","Operation":"UPDATE","OperationStatus":"IN_PROGRESS","RequestToken":"80e962a7-f324-4f3c-b98a-7988a76d66d0","ResourceModel":"{\"SplitChargeRules\":\"[ ]\",\"RuleVersion\":\"CostCategoryExpression.v1\",\"Arn\":\"arn:aws:ce::xxxxxxxxxxxx:costcategory/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"Rules\":\"[{\\n        \\\"Value\\\": \\\"Death and Taxes\\\",\\n        \\\"Rule\\\": {\\n            \\\"Dimensions\\\": {\\n                \\\"Key\\\": \\\"RECORD_TYPE\\\",\\n                \\\"Values\\\": [\\\"Tax\\\"],\\n                \\\"MatchOptions\\\": [\\\"EQUALS\\\"]\\n            }\\n        },\\n        \\\"Type\\\": \\\"REGULAR\\\"\\n    }]\",\"Name\":\"Pulumi Test Category 2\"}","TypeName":"AWS::CE::CostCategory"}}
```

Even though `SplitChargeRules` wasn't part of the patch document, it is present in the `ResourceModel` property of the response. The same thing happens when using AWS CLI v2 to send the update:

```
$ aws cloudcontrol update-resource --type-name AWS::CE::CostCategory --identifier arn:aws:ce::177190820489:costcategory/13bea2c7-7d69-4e89-82dd-0fb9558195aa --patch-document '[{"op":"replace","path":"Rules","value":"[{\"Value\":\"Life and Taxes\",\"Rule\":{\"Dimensions\":{\"Key\":\"RECORD_TYPE\",\"Values\":[\"Tax\"],\"MatchOptions\":[\"EQUALS\"]}},\"Type\":\"REGULAR\"}]"}]'
{
    "ProgressEvent": {
        "TypeName": "AWS::CE::CostCategory",
        "Identifier": "arn:aws:ce::xxxxxxxxxxxx:costcategory/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "RequestToken": "9702053f-d91a-4cb1-9383-a8b50b4ee358",
        "Operation": "UPDATE",
        "OperationStatus": "IN_PROGRESS",
        "EventTime": "2024-05-30T15:47:32.587000-07:00",
        "ResourceModel": "{\"SplitChargeRules\":\"[ ]\",\"RuleVersion\":\"CostCategoryExpression.v1\",\"Arn\":\"arn:aws:ce::xxxxxxxxxxxx:costcategory/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\"Rules\":\"[{\\\"Value\\\":\\\"Life and Taxes\\\",\\\"Rule\\\":{\\\"Dimensions\\\":{\\\"Key\\\":\\\"RECORD_TYPE\\\",\\\"Values\\\":[\\\"Tax\\\"],\\\"MatchOptions\\\":[\\\"EQUALS\\\"]}},\\\"Type\\\":\\\"REGULAR\\\"}]\",\"Name\":\"Pulumi Test Category 2\"}"
    }
}

$ aws cloudcontrol get-resource-request-status --request-token 9702053f-d91a-4cb1-9383-a8b50b4ee358
{
    "ProgressEvent": {
        "TypeName": "AWS::CE::CostCategory",
        "Identifier": "arn:aws:ce::xxxxxxxxxxxx:costcategory/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "RequestToken": "9702053f-d91a-4cb1-9383-a8b50b4ee358",
        "Operation": "UPDATE",
        "OperationStatus": "FAILED",
        "EventTime": "2024-05-30T15:47:32.871000-07:00",
        "StatusMessage": "1 validation error detected: Value '[]' at 'splitChargeRules' failed to satisfy constraint: Member must have length greater than or equal to 1 (Service: CostExplorer, Status Code: 400, Request ID: 09aaa2b9-7f16-430e-bb99-1059c1ee11d2)",
        "ErrorCode": "GeneralServiceException"
    }
}
```

I'll raise this issue with AWS instead.

**Comment by tvanbaak** [comment]
AWS replied to my ticket and confirmed that this is a bug on their side and an internal ticket has been filed.

**Comment by tvanbaak** [comment]
AWS got back to me last week with a workaround. They confirmed that the Cost Category team could replicate the issue and was working on a fix. In the meantime, they suggested the following workaround:

```
$ aws cloudcontrol update-resource --type-name AWS::CE::CostCategory --identifier "<costcategory-arn>" --patch-document '[{"op":"replace","path":"Rules","value":"[{\"Value\":\"Life and Taxes\",\"Rule\":{\"Dimensions\":{\"Key\":\"RECORD_TYPE\",\"Values\":[\"Tax\"],\"MatchOptions\":[\"EQUALS\"]}},\"Type\":\"REGULAR\"}]"}, {"op":"remove","path":"SplitChargeRules"}]'
```

i.e. it seems that you can avoid the split charge validation error by appending a `remove` to the patch document that removes the split charge rules that got added.

Unfortunately, this workaround doesn't unblock me using pulumi-aws-native because aws-native doesn't have a way to do it without a code patch. Would hacking in a special case for this be worthwhile? AWS Support didn't provide an ETA for when this would be properly resolved.

**Comment by corymhall** [comment]
@tvanbaak thanks for going through all the effort on this issue! I think it would take some figuring out how to special case this resource since I don't think we have done it before.

**Comment by tvanbaak** [comment]
AWS SUpport says they shipped the fix, and my local testing with pulumi-aws-native seems to confirm the bug is gone. Looks like a hack is unnecessary now.
