### ISSUE TITLE
Ec2 Instance: Shouldn't imageId and instanceType required?

### ISSUE THREAD

**Issue by druskus20** [pulumi/pulumi-aws-native#1717]
Looks like ec2.Instance's `instanceType` and `imageId` are required by AWS, however this requirement is not reflected in the typescript type, where the properties are optional (`?`). 

I work around this relatively easily since I create wrappers for some of the aws-native components - the following way: 

```ts
import * as pulumi from "@pulumi/pulumi";
import * as ec2 from "@pulumi/aws-native/ec2";
import * as inputs from "@pulumi/aws-native/types/input";

import { Resource } from "../resource";


export interface Ec2InstanceArgs {
  instance: InstanceArgs;
}

// Enforce some of the properties to be mandatory
export interface InstanceArgs extends ec2.InstanceArgs {
    /**
     * The ID of the AMI. An AMI ID is required to launch an instance and must be specified here or in a launch template.
     */
    imageId: pulumi.Input<string>;
    /**
     * The instance type.
     */
    instanceType: pulumi.Input<string>;
}

export class Ec2Instance extends Resource {
  public readonly instance_id: pulumi.Output<string>;

  constructor(
    name: string,
    args: Ec2InstanceArgs,
    opts?: pulumi.ComponentResourceOptions,
  ) {
    super(Ec2Instance, name, args, opts);
    
    const instance = new ec2.Instance(name, args.instance, { parent: this });
    this.instance_id = instance.id;

    this.registerOutputs({
      instance_id: this.instance_id
    });
  }
}
```

I am just wondering if there's a reason for this to be the case. (and also if you have any thoughts on my workaround and the general encapsulation pattern that I am using)

**Comment by flostadler** [comment]
Hey @druskus20, we generate the types for AWS native based on the CloudFormation Schema. Neither `instanceType` nor `imageId` are marked as required there (see [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html#aws-resource-ec2-instance-syntax)).

`imageId` needs to be set either directly on the EC2 instance or in the `launchTemplate`.
`instanceType` actually has a default in AWS: https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-ec2-default-instance-types.html

**Comment by druskus20** [comment]
Ah. Got it.
Thank you so much. I guess I can keep making abstractions for my specific use case like this. 

I believe you can close this issue.

**Comment by flostadler** [comment]
@druskus20 Awesome, thank you so much!
