### ISSUE TITLE
Missing regions in Region enum

### ISSUE THREAD

**Issue by spock-abadai** [pulumi/pulumi-aws-native#1726]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
There are a number of AWS Regions that are not available in awsn.Region. For example, il-central-1. Without support of these values it is impossible to instantiate a custom provider in typescript, for example, as it results in a compilation error.

This issue also existed in the classic AWS provider, was reported in https://github.com/pulumi/pulumi-aws/issues/4402 and fixed in https://github.com/pulumi/pulumi-aws/pull/4404. It should be fixed in aws native as well.

**Comment by flostadler** [comment]
@spock-abadai Thanks for making us aware of this! I'll tackle it right away
