### ISSUE TITLE
Refactor to ReplaceOnChanges annotations

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-aws-native#175]
If possible, get rid of our custom Diff logic in the provider. Instead, annotate schema properties with `ReplaceOnChanges` and rely on the engine to produce accurate diffs.

- [ ] Adjust codegen to set ReplaceOnChanges in the schema
- [ ] Adjust provider to rely on the engine to calculate diffs, including replacements

**Comment by danielrbradley** [comment]
As an update on this issue, I don't think we're able to fully move to engine-side diffs yet, so would need to continue doing the diff provider-side, but could annotate the properties with [`willReplaceOnChanges`](https://github.com/pulumi/pulumi/blob/a0f2c1c09e39a850c37e7d9621e41e1c0bbd7492/pkg/codegen/schema/schema.go) to surface the behaviour in the docs.

**Comment by mikhailshilkov** [comment]
Agreed! Do you want to change the title/description or close this issue as won't do and open a new one?

**Comment by danielrbradley** [comment]
Yes, let's close in favour of https://github.com/pulumi/pulumi-aws-native/issues/736
