### ISSUE TITLE
Handle missing auto-naming constraints

### ISSUE THREAD

**Issue by flostadler** [pulumi/pulumi-aws-native#1816]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The CloudFormation schema provided by AWS, which we use to generate the AWS Native provider metadata, lacks resource name length constraints for many AWS services. This is particularly problematic for resources like `lambda.Function` and `iam.Role` where AWS enforces strict length limitations (e.g., 64 characters for Lambda Role names) at the API level.

When users rely on the provider's auto-naming feature, deployments can fail unexpectedly because the provider isn't aware of these AWS-imposed limits. Since these constraints aren't present in the CloudFormation schema, the provider cannot validate or handle resource names appropriately before deployment.

### Proposal
Enhance provider metadata with length constraints for common AWS resources:
   - Manually add known length limits for popular resources (e.g., IAM Roles, Lambda Functions)
   - Implement intelligent name handling for resources exceeding limits
     - When auto-naming is enabled, trim long names while preserving uniqueness
       - Example: For a 100-character resource name with a 64-character limit, trim to 56 characters and append the random suffix (similar to AWS CloudFormation's approach)

Considerations:
   - This change should be non-breaking as resources exceeding AWS limits are currently undeployable with auto-naming. But it cannot rely only on the CloudFormation schema for constraint validation as it might be incorrect
       - Existing resources should retain their current names from state
   - Should document the auto-trimming behavior for transparency

### Affected area/feature

- aws-native
- pulumi-cdk

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/2191
