### ISSUE TITLE
Unable to create new S3 buckets with Typescript package

### ISSUE THREAD

**Issue by bryanmig** [pulumi/pulumi-aws-native#183]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Following [the docs](https://www.pulumi.com/registry/packages/aws-native/api-docs/s3/bucket/), I tried to create a new S3 bucket using the `@pulumi/aws-native` TypeScript package but when run, it results in an error.

I have verified that the AWS region is correctly specified in both my AWS profile as well as in the Pulumi config file.

### Steps to reproduce

Attempt to create a new bucket with no additional parameters specified, per the documentation examples
```
import * as aws_native from "@pulumi/aws-native";
const s3Bucket = new aws_native.s3.Bucket("s3Bucket", {});
```

Expected: Bucket would be created
Actual: An error is returned staging that the region is required
```
Diagnostics:
  aws-native:s3:Bucket (s3Bucket):
    error: missing required property 'region'
```

**Comment by pierskarsenbarg** [comment]
Hi @bryanmig have you followed the [Installation and configuration guide](https://www.pulumi.com/registry/packages/aws-native/installation-configuration/) which also gives you information about [how to configure the provider](https://www.pulumi.com/registry/packages/aws-native/installation-configuration/#configuration-options)? 

You'll need to set the region in your config, and you can do this by running `pulumi config set aws:region {region}`.

**Comment by bryanmig** [comment]
Yes - confirming that this was the issue.  I had to update the config prefix to `aws-native`
