### ISSUE TITLE
stepfunctions StateMachine Create Bug

### ISSUE THREAD

**Issue by SeanWei-lab** [pulumi/pulumi-aws-native#1830]
### What happened?

I have a problem creating a StepFunction StateMachine using the aws-native plugin. I have two stacks, one of which is a test Stack, with the following code:
stepfunctions.StateMachine(
    f"{function_name}StateMachine",
    state_machine_name=f"{function_name}-StateMachine",
    state_machine_type=stepfunctions.StateMachineType.STANDARD,
    definition_string=json.dumps(step_function_machine_json),
    role_arn=execution_role
)
This creation works fine.
But my other production Stack code is as follows:
stepfunctions.StateMachine(
    f"{function_name}StateMachine",
    state_machine_name=f"{function_name}-StateMachine",
    state_machine_type=stepfunctions.StateMachineType.STANDARD,
    definition_string=json.dumps(step_function_machine_json),
    role_arn=self.params["execution_role"]
)
Error occurred when running production code： NameError: name 'StateMachineDefinitionArgs' is not defined

Because I tested that the stack is fine and the production stack has a problem, so I feel this is a bug.

### Example

stepfunctions.StateMachine(
    f"{function_name}StateMachine",
    state_machine_name=f"{function_name}-StateMachine",
    state_machine_type=stepfunctions.StateMachineType.STANDARD,
    definition_string=json.dumps(step_function_machine_json),
    role_arn=self.params["execution_role"]
)

### Output of `pulumi about`

CLI          
Version      3.138.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.49.1
resource  aws-native  1.8.0
language  python      unknown

Host     
OS       darwin
Version  15.0.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Hey @SeanWei-lab, sorry you're running into issues here!

I don't seem to be able to reproduce this. I created this program based on your example and it's deploying successfully:
```
import pulumi_aws_native as aws_native
from pulumi_aws_native import stepfunctions

step_function_role = aws_native.iam.Role("stepFunctionRole",
    assume_role_policy_document="""{
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "states.amazonaws.com"
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }
    """
)

state_machine = aws_native.stepfunctions.StateMachine("myStateMachine",
    role_arn=step_function_role.arn,
    state_machine_type=stepfunctions.StateMachineType.STANDARD,
    definition_string="""
    {
      "Comment": "A simple AWS Step Functions state machine example",
      "StartAt": "HelloWorld",
      "States": {
        "HelloWorld": {
          "Type": "Pass",
          "Result": "Hello, World!",
          "End": true
        }
      }
    }
    """,
    state_machine_name="myStateMachine"
)
```

Could you provide a full repro so we can further debug this? Thanks!
