### ISSUE TITLE
S3 Bucket not created with correct name

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws-native#199]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When creating an s3 bucket, it doesn't use the resource name.

### Steps to reproduce
Use following code:

```typescript
import * as aws from "@pulumi/aws-native";

const bucket = new aws.s3.Bucket("awsnativebucket");

export const bucketid = bucket.id;
```

Expected: 

bucketid output would be something like `awsnativebucket` or `awsnativebucket-xxxxxx` (depending whether autonaming had been added yet)

Actual: 

`bucketid: "peccfbjcpsjqqck6enmut7xeb-6ieta8apm2be"`

**Comment by mikhailshilkov** [comment]
This is by design - until autonaming lands, there's no relation between the logical name of a `Bucket` and its name in AWS. You'd need to set it in `bucketName` explicitly.
