### ISSUE TITLE
Config value for `region` is ignored but the environment variables are not.

### ISSUE THREAD

**Issue by inhumantsar** [pulumi/pulumi-aws-native#218]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Config value for `region` is ignored but the environment variables are not.

### Steps to reproduce

```
$ pulumi version  
v3.17.1

$ pip freeze | grep pulumi
pulumi==3.17.1
pulumi-aws==4.25.0
pulumi-aws-native==0.4.0
```

```yaml
config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  ...
```

```
$ pulumi destroy -y
...
  aws-native:ecs:Service (my-ecs-service):
    error: missing required property 'region'
```

```
$ export AWS_DEFAULT_REGION=us-east-1
$ pulumi destroy -y
... success ...
```

**Comment by mikhailshilkov** [comment]
This is very surprising... I'm using the config variable locally, definitely no env variable set, and yet it works fine. Any chance you could send your debug logs to mikhail@pulumi.com to take a look?

**Comment by inhumantsar** [comment]
False alarm I guess. Unable to repro
