### ISSUE TITLE
Failed to import `OIDCProvider` - `failed to fetch provider schema: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8`

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-aws-native#300]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to import and `OIDCProvider` using the AWS Native provider but so far it's been failing.
After many attempts and following the guidance in #293, I think the correct syntax should be `pulumi import aws-native:iam:OIDCProvider aureq-oidcProvider arn:aws:iam::052848974346:oidc-provider/oidc.eks.ap-southeast-2.amazonaws.com/id/9B5F36930BA8AEEAFEAB80044382244C`

However, the error I get is: `ERROR: 2022/01/04 04:25:23 [core] grpc: server failed to encode response:  rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8`

Note: This may already have been fixed in #287 

### Steps to reproduce

1. Create an OIDC Provider in the IAM console
2. run the corresponding command above
3. Get the error message

Expected: The resource is imported
Actual: An internal error occured

**Comment by stack72** [comment]
Hi @aureq 

Can you retry this again using the latest version of the provider now that we have a better import story?

Paul

**Comment by aureq** [comment]
@stack72 Yes, I confirm this is working now and the code is also generated at the end of the import. 

@orcutt989 Please give it a go.

I'm marking this issue as closed.

**Comment by stack72** [comment]
Thanks @aureq :)
