### ISSUE TITLE
VPC opensearchservice domain - extraneous key [vpc] is not permitted

### ISSUE THREAD

**Issue by hamuk** [pulumi/pulumi-aws-native#304]
## Hello!

I've noticed an issue when trying to make changes to an open search service domain in a VPC after it has been created. 

## Example 
I created a domain in a VPC like so:
```
const esDomain = new awsnative.opensearchservice.Domain(ES_NAME, {
  clusterConfig: {
    instanceType: "t3.small.search",
    instanceCount: 1,
  },
  vPCOptions: {
    subnetIds: esSubnet,
    securityGroupIds: [esSecurityGroup.id],
  },
  eBSOptions: {
    eBSEnabled: true,
    volumeSize: 10,
  },
  accessPolicies: {
    Version: "2012-10-17",
    Statement: [
      {
        Principal: "*",
        Action: ["es:*"],
        Effect: "Allow",
        Resource: "*",
      },
    ],
  },
});
```

After running ```pulumi up``` and it creating the initial resource if I try to change any part of it (e.g. accessPolicies) I get the following error:
```
error: operation error CloudControl: UpdateResource, https response error StatusCode: 400, RequestID: [omitted], api error ValidationException: Model validation failed (#/DomainEndpoints: extraneous key [vpc] is not permitted)
```

Cheers

**Comment by marcin-ro** [comment]
I ran into the same thing, any change to an `opensearchservice.Domain` is rejected with that `extraneous key [vpc] is not permitted`.

Additionally, when I add `--logtostderr` to try to poke at this I get `AccessDeniedException: User: XXX is not authorized to perform: cloudformation:UpdateResource on resource: arn:aws:cloudformation:YYY:ZZZ:resource/* because no identity-based policy allows the cloudformation:UpdateResource action`.

**Comment by viveklak** [comment]
Trying to reproduce this, it appears to be an issue with the CloudControl. Our payload to UpdateResource looks valid, e.g.:
```
X-Amz-Target: CloudApiService.UpdateResource
...
{"ClientToken":"XXXX","Identifier":"esdomain-c6209e6","PatchDocument":"[{\"op\":\"replace\",\"path\":\"/AccessPolicies\",\"value\":{\"Statement\":[{\"Action\":[\"es:*:*\"],\"Effect\":\"Allow\",\"Principal\":\"*\",\"Resource\":\"*\"}],\"Version\":\"2012-10-17\"}}]","TypeName":"AWS::OpenSearchService::Domain"}
```
and we get the following response:
```
HTTP/1.1 400 Bad Request
Content-Length: 153
Content-Type: application/x-amz-json-1.0
X-Amzn-Requestid: XXX
 {"__type":"com.amazon.coral.validate#ValidationException","message":"Model validation failed (#/DomainEndpoints: extraneous key [vpc] is not permitted)"}
```
Perhaps this coming from calls from Cloud Control to open search service. Will raise it with our AWS contacts.

@marcin-ro - I didn't see the access denied issue. Perhaps the IAM user you are running with has insufficient IAM privileges?

**Comment by marcin-ro** [comment]
@viveklak Thanks for checking!

> I didn't see the access denied issue. Perhaps the IAM user you are running with has insufficient IAM privileges?

I might be missing something, does `--logtostderr` require additional privileges?

**Comment by marcin-ro** [comment]
Hi @viveklak!  Just checking: was this reported up, is there maybe a public ticket I could also follow?

**Comment by viveklak** [comment]
@marcin-ro apologies for the delay. Unfortunately we don't have a public channel yet - we are working on this with our AWS partners. @danielrbradley - would you be able to follow-up on this?

> I might be missing something, does --logtostderr require additional privileges?

No. Looking at the error again, the authorization error also looks like something that the CloudControl service is encountering. Are you running things with an IAM user? You might have to make sure the IAM user has the following actions whitelisted:
```
"cloudformation:CreateResource",
"cloudformation:GetResource",
"cloudformation:UpdateResource",
"cloudformation:ListResources",
"cloudformation:DeleteResource"
```

See https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/security.html for reference.

@stack72 we might have to call out the above in the package docs for aws-native, perhaps in
https://www.pulumi.com/registry/packages/aws-native/installation-configuration/#get-your-credentials ?

**Comment by danielrbradley** [comment]
Yup, the AWS OpenSearch team are aware of the possible issue and we're waiting for them to investigate further.

**Comment by danielrbradley** [comment]
This should have been resolved as of April 24th
