### ISSUE TITLE
[OpenSearch Service] Zone awareness not configurable

### ISSUE THREAD

**Issue by boernd** [pulumi/pulumi-aws-native#425]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

According to [AWS CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-zoneawarenessconfig.html) it should be possible to set `ZoneAwarenessConfig` in the domain specs.

This seems to be missing in the code, e.g. https://github.com/pulumi/pulumi-aws-native/blob/master/sdk/python/pulumi_aws_native/opensearchservice/domain.py

**Comment by guineveresaenger** [comment]
Hi @boernd -

It does look like this feature is not yet implemented for this provider. We'll take a look as soon as we can, and in the meantime, would welcome any assistance you could offer.

**Comment by viveklak** [comment]
@boernd you can specify ZoneAwarenessConfig through the [`zone_awareness_config`](https://www.pulumi.com/registry/packages/aws-native/api-docs/opensearchservice/domain/#zone_awareness_config_python) field in https://www.pulumi.com/registry/packages/aws-native/api-docs/opensearchservice/domain/#domainclusterconfig. FWIW the inputs are emitted to [`_inputs.py`](https://github.com/pulumi/pulumi-aws-native/blob/master/sdk/python/pulumi_aws_native/opensearchservice/_inputs.py) file.
