### ISSUE TITLE
ValidationException (keyword [pattern]) of s3.Bucket tags 

### ISSUE THREAD

**Issue by Iced-Sun** [pulumi/pulumi-aws-native#435]
## Issue details

Cloud Control API is available in aws-cn recently ([link](https://www.amazonaws.cn/en/new/2022/amazon-cloud-control-api-available-amazon-web-services-china-regions/?nc1=h_ls)), so I decide to play with aws-native.

It seems that the allowed characters are very restricted in tags (both key and value), at least in s3.Bucket.

### Steps to reproduce

```typescript
new awsnative.s3.Bucket('bucket', {
  tags: [{
    key: 'broken:key', value: 'value'
  }, {
    key: 'key', value: 'broken@value'
  }]
});
```

Expected: 

The bucket tags should be created fine.

Actual: 

Throw runtime error `api error ValidationException: Model validation failed (#/Tags/0/Key: failed validation constraint for keyword [pattern]   #/Tags/1/Value: failed validation constraint for keyword [pattern])`.

**Comment by jkodroff** [comment]
Confirmed these are valid tag values via the AWS console.

**Comment by mikhailshilkov** [comment]
Tried the repro above today and it works now
