### ISSUE TITLE
The binary `cf2pulumi` is missing in v0.15.0

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-aws-native#448]
### What happened?

As of v0.15.0, it appears that `cf2pulumi` is no longer available.

### Steps to reproduce

1. Go to v0.15.0 release page https://github.com/pulumi/pulumi-aws-native/releases/tag/v0.15.0
2. Check if `cf2pulumi` binaries are available

### Expected Behavior

`cf2pulumi` binaries are available for download.

### Actual Behavior

`cf2pulumi` binaries are missing.

### Versions used

v0.15.0

### Additional context

Maybe it's related to #151

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
@stack72 @viveklak I see v0.16.0 was also missing `cf2pulumi` but v0.16.1 has it. Is it safe to close this issue or should we keep it for now?

**Comment by viveklak** [comment]
@aureq Apologies, I believe the publish issue was conclusively fixed in https://github.com/pulumi/pulumi-aws-native/commit/bb0a2bd639148805af5f1476f036b4556753e795 which went in after 0.16.0 (in 0.16.1). I think we can close this.

**Comment by aureq** [comment]
Great, thank you so much @viveklak
