### ISSUE TITLE
Can't deploy a fully working Lambda Function URL example

### ISSUE THREAD

**Issue by Tirke** [pulumi/pulumi-aws-native#450]
### What happened?

[The pulumi article](https://www.pulumi.com/blog/lambda-urls-launch/) on Lambda Function URL doesn’t contain a working example. I can’t call the URL that is created because the Lambda is lacking a critical permission (`lambda:InvokeFunctionUrl`) and I don’t know how to add it because I don’t know how to add the necessary condition using the classic `aws.lambda.Permission` resource. Any help? (edited)

### Steps to reproduce

It's the same code as the article
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsnative from "@pulumi/aws-native";

const lambdaRole = new awsnative.iam.Role("lambdaRole", {
  assumeRolePolicyDocument: {
    Version: "2012-10-17",
    Statement: [
      {
        Action: "sts:AssumeRole",
        Principal: {
          Service: "lambda.amazonaws.com",
        },
        Effect: "Allow",
        Sid: "",
      },
    ],
  },
});

const lambdaRoleAttachment = new aws.iam.RolePolicyAttachment(
  "lambdaRoleAttachment",
  {
    role: pulumi.interpolate`${lambdaRole.roleName}`,
    policyArn: aws.iam.ManagedPolicy.AWSLambdaBasicExecutionRole,
  }
);

const helloFunction = new awsnative.lambda.Function("helloFunction", {
  role: lambdaRole.arn,
  runtime: "nodejs14.x",
  handler: "index.handler",
  code: {
    zipFile: `exports.handler = function(event, context, callback){ callback(null, {"response": "Hello "}); };`,
  },
});

const lambdaUrl = new awsnative.lambda.Url("test", {
  targetFunctionArn: helloFunction.arn,
  authType: awsnative.lambda.UrlAuthType.None,
});

export const url = lambdaUrl.functionUrl;
```

Then you curl the url and it fails because the Lambda is missing the permission
```
curl https://v2fcp4tpzqi5jclbrwuhctiy340uorfl.lambda-url.eu-central-1.on.aws/
{"Message":"Forbidden"}
```

Here is an exemple of the correct permission I need to add to the lambda for the public URL to work
```


Statement ID: FunctionURLAllowPublicAccess
Principal: *
Effect: Allow
Action: lambda:InvokeFunctionUrl
Conditions
{
 "StringEquals": {
  "lambda:FunctionUrlAuthType": "NONE"
 }
}
```

### Expected Behavior

I should have a way to deploy the needed lambda permissions to allow calling a function URL.

### Actual Behavior

I can't call the endpoint because I'm missing a permission on the Lambda.

### Versions used

```
CLI
Version      3.28.0
Go Version   go1.18
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.1.2
aws         5.1.2
aws         5.1.2
aws         5.1.0
aws         5.1.0
aws-native  0.15.0
aws-native  0.15.0
docker      3.1.0
docker      3.1.0
docker      3.1.0
docker      3.1.0
nodejs      unknown

Host
OS       darwin
Version  12.3
Arch     arm64

This project is written in nodejs (/Users/tirke/Library/Caches/fnm_multishells/42441_1649928408698/bin/node v16.14.2)
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Tirke** [comment]
I guess what's missing [is `FunctionUrlAuthType`].(https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#:~:text=Update%20requires%3A%20Replacement-,FunctionUrlAuthType,-The%20type%20of)

**Comment by aureq** [comment]
Have you checked if the function actually exists in the AWS Management Console?

**Comment by guineveresaenger** [comment]
Hi @Tirke - thank you for reporting this and for doing some legwork on it. You are correct - due to changes to AWS, our example is currently broken. I tried it and ran into `Message:Forbidden` as well.

Please stay tuned as we work to fix this with the most up to date resource schema.

**Comment by pierskarsenbarg** [comment]
@Tirke as a workaround, you can use the [Pulumi Command](https://www.pulumi.com/registry/packages/command/) provider.

If you add the following just above the `export const...` line:

```typescript
const awsCommand = new local.Command("aws-command", {
    create: pulumi.interpolate`aws lambda add-permission --function-name ${helloFunction.functionName} --action lambda:InvokeFunctionUrl --principal '*' --function-url-auth-type NONE --statement-id FunctionURLAllowPublicAccess`
}, {deleteBeforeReplace: true, dependsOn: [helloFunction]});
```

That will run the AWS CLI on whatever machine is running the code. This means you'll need it on whatever machine you're running the Pulumi program on it (so local laptop, CI/CD machine etc).

There's also going to be an update to the blog post containing this going out soon

**Comment by Tirke** [comment]
@pierskarsenbarg That a way to unblock things while waiting on either that one https://github.com/pulumi/pulumi-aws/pull/1902 or a fix to the native provider. Thanks a lot :)

**Comment by pierskarsenbarg** [comment]
I've updated the blog post with the necessary changes to be able to deploy lambda functions.

For the full automation with Go, we need to wait for [this issue](https://github.com/pulumi/pulumi-command/issues/53)

**Comment by FilipLeonard** [comment]
I just recreated the blog resources using `aws.lambda.FunctionUrl` and `aws.lambda.Function` instead of the `awsnative` counterparts, did not create any `Command`, and the lambda was created with the right `lambda:InvokeFunctionUrl` permission.

**Comment by maxcan** [comment]
@pierskarsenbarg that command workaround, as detailed in the blog, doesn't work because pulumi considers `${function.functionName}` to be a secret so it is obscured in the command output.

**Comment by danielrbradley** [comment]
Another workaround here is to use the lambda Permission resource from the bridged AWS provider until this is fully supported by CloudControl.

```typescript
const publicInvokePermission = new aws.lambda.Permission("public-invoke-permission", {
  function: func.functionName.apply((n) => n!), // Avoid typescript warning us that the function name output is optional
  action: "lambda:InvokeFunctionUrl",
  principal: "*",
  functionUrlAuthType: "NONE",
  statementId: "FunctionURLAllowPublicAccess",
});
```

**Comment by flostadler** [comment]
aws-native now supports Lambda Permissions since `v0.71.0`: https://www.pulumi.com/registry/packages/aws-native/api-docs/lambda/permission/
