### ISSUE TITLE
Redshift EndpointAuthorization validation for VPC id restricts to numeric instead of alphanumeric

### ISSUE THREAD

**Issue by jspiewak** [pulumi/pulumi-aws-native#460]
### What happened?

I am attempting to create a Redshift EndpointAuthoization.
The resource fails to create with the error:

```
  aws-native:redshift:EndpointAuthorization (main-redshift-authn):
    error: creating resource: operation error CloudControl: CreateResource, https response error StatusCode: 400, RequestID: 0f4e1bab-ca27-408b-bec2-45fd1143636f, api error ValidationException: Model validation failed (#/VpcIds/0: failed validation constraint for keyword [pattern])
```

The [pattern](https://github.com/pulumi/pulumi-aws-native/blob/master/aws-cloudformation-schema/aws-redshift-endpointauthorization.json#L12) is "^vpc-\\d{1,17}$", which restricts to numeric. It needs to be alphanumeric.

### Steps to reproduce

Attempt to create a Redshift EndpointAuthorization with a VPC id that is alphanumeric.

### Expected Behavior

I expect alphanumeric VPC ids to succeed.

### Actual Behavior

They fail.

### Versions used

CLI          
Version      3.29.1
Go Version   go1.17.8
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.1.3
aws-native  0.15.0
python      unknown

Host     
OS       darwin
Version  12.3.1
Arch     arm64

### Additional context

Likely an AWS issue, but pretty egregious.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Tracked in #1346
