### ISSUE TITLE
multiple syntax errors in get_web_aclassociation.py

### ISSUE THREAD

**Issue by cbcmg** [pulumi/pulumi-aws-native#482]
https://github.com/pulumi/pulumi-aws-native/blob/1ae4a4d9c2256b2a79ca536f8d8497b28d10e4c3/sdk/python/pulumi_aws_native/wafv2/get_web_aclassociation.py#L21

**Comment by mikhailshilkov** [comment]
This file doesn't exist anymore, closing as fixed
