### ISSUE TITLE
aws::RedshiftServerless::Workgroup Supported by CCAPI not yet in AWS Native

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws-native#594]
This resource is supported in CCAPI: https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html

But is not in AWS Native: https://www.pulumi.com/registry/packages/aws-native/api-docs/

We should have [nightly releases with the latest CCAPI resources available](https://www.pulumi.com/blog/announcing-aws-native/), right?

> The AWS Native provider offers same-day support for all new AWS features and releases covered by the newly released [AWS Cloud Control API](https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api), which typically supports new AWS features on the day of launch

**Comment by stack72** [comment]
This will come in as part of v0.21.0 tomorrow :)

**Comment by stack72** [comment]
Closed via #600
