### ISSUE TITLE
Ability to do AWS backup of DynamoDB resource

### ISSUE THREAD

**Issue by bolinocroustibat** [pulumi/pulumi-aws-native#606]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would seem `pulumi_aws.backup.Plan` (and therefore AWS native) only support `EC2` as `resource_type` value in `PlanAdvancedBackupSetting`, meaning it can only backup EC2 instances, and not DynamoDB resources for example:
https://www.pulumi.com/registry/packages/aws/api-docs/backup/plan/#planadvancedbackupsetting

Any plan to add other AWS resources, like DynamoDB tables, to be supported in AWS backup plans?

### Affected area/feature

Pulumi AWS backup plan (`backup.Plan`)

**Comment by guineveresaenger** [comment]
Hi @bolinocroustibat - thank you for this enhancement request. We'll take a look as soon as we are able!

**Comment by mjeffryes** [comment]
The docs linked are for the AWS provider; AWS native does support the full range of values for  this parameter: https://www.pulumi.com/registry/packages/aws-native/api-docs/backup/backupplan/#backupplanadvancedbackupsettingresourcetype
