### ISSUE TITLE
Unable to create Redshift serverless workgroup

### ISSUE THREAD

**Issue by alexbowers** [pulumi/pulumi-aws-native#614]
### What happened?

An error and failure happens when trying to create a workgroup.

### Steps to reproduce

Create a namespace:
```
 const namespace = new redshiftserverless.Namespace('Jobilla Redshift Namespace', {
            namespaceName: 'jobilla',
        });
```

Then try to create a workgroup:

```
const workgroup = new redshiftserverless.Workgroup('Jobilla Redshift Workgroup', {
    namespaceName: namespace.namespaceName,
    workgroupName: 'jobilla',
    publiclyAccessible: true,
});
```

and you will get the following error:

```error: resource partially created but read failed. read error: reading resource state: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: cb82774f-c39e-4183-9cc6-579d2c30cd05, ResourceNotFoundException: AWS::RedshiftServerless::Workgroup Handler returned status FAILED: Serverless workgroup jobilla not found. (Service: RedshiftServerless, Status Code: 400, Request ID: 5d9fa523-8a30-4ad1-afd5-5e276b4ac0a2) (HandlerErrorCode: NotFound, RequestToken: f819bce7-de38-445e-8d43-86f0f39a671f), create error: operation CREATE failed with "InvalidRequest": VPC Security group sg-00a34b1e2214f18b9 does not exist in VPC vpc-0723885b2b7fdb933 (Service: RedshiftServerless, Status Code: 400, Request ID: a221c836-155a-4da5-8f23-f30b0d1f3688)```

### Expected Behavior

The workgroup gets created and works

### Actual Behavior

```error: resource partially created but read failed. read error: reading resource state: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: cb82774f-c39e-4183-9cc6-579d2c30cd05, ResourceNotFoundException: AWS::RedshiftServerless::Workgroup Handler returned status FAILED: Serverless workgroup jobilla not found. (Service: RedshiftServerless, Status Code: 400, Request ID: 5d9fa523-8a30-4ad1-afd5-5e276b4ac0a2) (HandlerErrorCode: NotFound, RequestToken: f819bce7-de38-445e-8d43-86f0f39a671f), create error: operation CREATE failed with "InvalidRequest": VPC Security group sg-00a34b1e2214f18b9 does not exist in VPC vpc-0723885b2b7fdb933 (Service: RedshiftServerless, Status Code: 400, Request ID: a221c836-155a-4da5-8f23-f30b0d1f3688)```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
I tried running this myself and didn't hit the problem you mentioned. Documentation is a bit lax on the semantics here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshiftserverless-workgroup.html but it appears the workgroup is created in the default VPC and uses the default security group. Perhaps you can see what is special about the VPC and security group mentioned in the error:
```
VPC Security group sg-00a34b1e2214f18b9 does not exist in VPC vpc-0723885b2b7fdb933
```

**Comment by alexbowers** [comment]
This is not the default SG or VPC, this is a specific VPC created by ourselves that is used for the rest of our services (and has not caused import problems with other resources).

We are using `eu-north-1` and a custom VPC. We are also assuming role into a secondary account. That is the only non-default setup we have as far as I can think.

**Comment by mikhailshilkov** [comment]
Hi @alexbowers I'm sorry for a very long silence on our side.

Do you still experience this issue? Any chance you could provide us with a full repro to see the issue in action?

**Comment by mjeffryes** [comment]
Closing this for now since we haven't heard back for a while. Feel free to reopen if you're still experiencing this issue and have a repro case for us to investigate!
