### ISSUE TITLE
ECS Task Definition ignores user-provided name

### ISSUE THREAD

**Issue by xiongchiamiov** [pulumi/pulumi-aws-native#619]
### What happened?

I'm creating a task definition for ECS and providing a human-readable resource name so that I can recognize task definitions while looking in the AWS console.

### Steps to reproduce

Here is my Pulumi code:

```python3
"""An AWS Python Pulumi program"""

import pulumi
from pulumi_aws_native import ecs

task_definition = ecs.TaskDefinition(
    resource_name='winnie-web-task-{}'.format(pulumi.get_stack()),
    requires_compatibilities=['FARGATE'],
    cpu='1024',
    memory='2048',
    container_definitions=[
        ecs.TaskDefinitionContainerDefinitionArgs(
            name='nginx',
            image='755158074228.dkr.ecr.us-west-2.amazonaws.com/winnie-nginx:1.0.4',
            essential=True,
        ),
    ],
    network_mode='awsvpc',
    runtime_platform=ecs.TaskDefinitionRuntimePlatformArgs(
        operating_system_family='Linux',
    ),
    execution_role_arn='arn:aws:iam::755158074228:role/ecsTaskExecutionRole',
)
```
(This is a private image, but should work with [the public example in the docs](https://www.pulumi.com/registry/packages/aws-native/api-docs/ecs/taskdefinition/#example).)

pip freeze:
```
Arpeggio==1.10.2
attrs==22.1.0
dill==0.3.5.1
grpcio==1.47.0
parver==0.3.1
protobuf==4.21.5
pulumi==3.39.3
pulumi-aws-native==0.29.0
PyYAML==6.0
semver==2.13.0
six==1.16.0
```

### Expected Behavior

I'd expect to see the task named something like `winnie-web-task-staging-<suffix>`.

### Actual Behavior

The resource is named `M0JVujF1TeMX9JUzAj3feASVC-I7fArcNDlnCE`.

### Output of `pulumi about`

```CLI          
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME        VERSION
aws-native  0.29.0
python      unknown

Host     
OS       darwin
Version  12.5.1
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.10.6
'

Current Stack: staging

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:staging::aws::pulumi:pulumi:Stack::aws-staging
pulumi:providers:aws-native    urn:pulumi:staging::aws::pulumi:providers:aws-native::default_0_29_0
aws-native:ecs:TaskDefinition  urn:pulumi:staging::aws::aws-native:ecs:TaskDefinition::winnie-web-task-staging
aws-native:ecs:Cluster         urn:pulumi:staging::aws::aws-native:ecs:Cluster::winnie


Found no pending operations associated with staging

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/xiongchiamiov
User           xiongchiamiov
Organizations  xiongchiamiov

Dependencies:
NAME               VERSION
pip                22.2.2
pulumi-aws-native  0.29.0
setuptools         65.3.0
wheel              0.37.1

Pulumi locates its logs in /var/folders/v9/9fdfk9j109ndft37cst980c00000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
Here is some information about why Pulumi uses autonaming and how to override it if needed: https://www.pulumi.com/docs/intro/concepts/resources/names/#autonaming

**Comment by xiongchiamiov** [comment]
@jkisk Yep, I had read that.

> If the name property is not available on a resource, consult the [Registry](https://www.pulumi.com/registry/) for the specific resource you are creating. Some resources use a different property to override auto-naming. For instance, the aws.s3.Bucket type uses the property bucket instead of name.

And as far as I can tell from [the documentation](https://www.pulumi.com/registry/packages/aws-native/api-docs/ecs/taskdefinition/#create), that is the intent of `resource_name` in `TaskDefinition` - it's described as "the unique name of the resource".

Task definitions _do_ have user-assignable names in AWS, so it would make sense that this would be used from the field in Pulumi.  If this is one of the resources that only uses autogenerated ids, however, that should be clarified in the documentation and the actual usage of `resource_name` should be covered - since right now it appears to be entirely ignored and unused.

**Comment by jkisk** [comment]
Thanks for updating, I'll reopen so it can be considered for further work

**Comment by xiongchiamiov** [comment]
Here's an updated minimum reproducible test case:

Pulumi code:
```python3
def unused_resource_name():
    task_definition = ecs.TaskDefinition(
        resource_name='a-cool-unique-name',
        container_definitions=[
            ecs.TaskDefinitionContainerDefinitionArgs(
                name="my-app",
                image="amazon/amazon-ecs-sample",
                memory=128,
            )
        ],
    )
    pulumi.export('name', task_definition.task_definition_arn)
```
Or clone https://github.com/xiongchiamiov/pulumi-bug-reports/tree/main/aws-native-python and call the function `ecs_task_definition.unused_resource_name()`.

Pulumi output:
```
┌─[jamesph@Jamess-MBP] - [~/Documents/pulumi-bug-reports/aws-native-python] - [Mon Sep 19, 03:59]
└─[$]> pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/xiongchiamiov/aws-native-python/dev/previews/727ea191-edbf-4a5e-81dd-fc98c0788178

     Type                              Name                   Plan
 +   pulumi:pulumi:Stack               aws-native-python-dev  create
 +   └─ aws-native:ecs:TaskDefinition  a-cool-unique-name     create

Outputs:
    name: output<string>

Resources:
    + 2 to create

Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/xiongchiamiov/aws-native-python/dev/updates/10

     Type                              Name                   Status
 +   pulumi:pulumi:Stack               aws-native-python-dev  created
 +   └─ aws-native:ecs:TaskDefinition  a-cool-unique-name     created

Outputs:
    name: "arn:aws:ecs:us-west-2:755158074228:task-definition/mR4mkhFLLdCuc5S8F5n481kW2-TJpjhre6n2cl:1"

Resources:
    + 2 created

Duration: 5s

warning: A new version of Pulumi is available. To upgrade from version '3.39.3' to '3.40.1', run
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```
The ARN there is what I would expect to contain the string "a-cool-unique-name".

**Comment by mikhailshilkov** [comment]
`resource_name='a-cool-unique-name',` is a logical resource name in Pulumi stack, it's not passed up to AWS API. It looks like there is no explicit name property in Cloud Formation's model of ECS Task Definition.
