### ISSUE TITLE
Descriptions are missing in API docs

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-aws-native#63]
Our current API docs are missing textual descriptions for resource and property descriptions. We put API doc links instead which won't lead to a good API doc user experience. We need to retrieve the docs instead.

**Comment by viveklak** [comment]
FWIW json schemas are often pretty scant on the descriptions so at the moment, our api docs are pretty anemic when it comes to property descriptions. See https://github.com/pulumi/docs/issues/8102#issuecomment-1275625976 for instance.

**Comment by viveklak** [comment]
FYI @danielrbradley
