### ISSUE TITLE
Lightsail Distribution is supported now?

### ISSUE THREAD

**Issue by kevinresol** [pulumi/pulumi-aws-native#634]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Apparently `AWS::Lightsail::Distribution` is already supported by the API? If so can we enable it in aws-native please?

![Screenshot 2022-09-23 at 17 15 04](https://user-images.githubusercontent.com/1103788/191913504-4ba4af31-028f-4eaf-a25d-fa7f23d26661.png)

**Comment by danielrbradley** [comment]
Our list of supported types is derrived from an AWS API request. Currently, AWS are not yet returning the Distribution type in their response. Once it's returned by their endpoint the resource will be available in the next release.
