### ISSUE TITLE
Amazon EventBridge Scheduler support

### ISSUE THREAD

**Issue by albertocorrales** [pulumi/pulumi-aws-native#697]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Recently, AWS introduced Amazon EventBridge Scheduler. https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/

We can use [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Scheduler.html) to create this resource, but we cannot create it with pulumi native or classic.

**Comment by thomas11** [comment]
Hi @albertocorrales, [version v0.41.0](https://github.com/pulumi/pulumi-aws-native/releases/tag/v0.41.0) that was released today includes the latest CloudFormation APIs and added resources `scheduler.Schedule` and `scheduler.ScheduleGroup`.
