### ISSUE TITLE
Dynamodb updating attributeDefinitions requires timeToLiveSpecification to be set

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws-native#730]
### What happened?

When updating the attributeDefinitions of a dynamodb table, the error arises that the timeToLiveSpecification property is not set. To my knowledge this is not documented anywhere. Checking the https://www.pulumi.com/registry/packages/aws-native/api-docs/dynamodb/table/#inputs page also does not mention this behavior.

### Steps to reproduce

```
const table = new aws.dynamodb.Table("table", {
  attributeDefinitions: [
    {
      attributeName: "test",
      attributeType: "S",
    },
    {
      attributeName: "Part",
      attributeType: "S",
    },
    // Add this attribute after creation, then run pulumi up to receive the error.
    {
      attributeName: "Value",
      attributeType: "S",
    },
  ],
  keySchema: [
    {
      attributeName: "test",
      keyType: "HASH",
    },
    {
      attributeName: "Part",
      keyType: "RANGE",
    },
  ],
  tableName: "table",
  billingMode: "PAY_PER_REQUEST",
});
```

### Expected Behavior

Documentation and an example of the requirement of the timeToLiveSpecification property.

### Actual Behavior

```
aws-native:dynamodb:Table (table):
    error: operation error CloudControl: UpdateResource, https response error StatusCode: 400, RequestID: 0fe14e83-9362-4d8d-8656-83ccc015a9e0, api error ValidationException: Model validation failed (#/TimeToLiveSpecification: required key [AttributeName] not found)
```

### Output of `pulumi about`

```
Dependencies:
NAME                VERSION
@pulumi/aws         5.23.0
@pulumi/aws-native  0.43.0
@pulumi/pulumi      3.48.0
```

### Additional context

Please note that for the creation of the dynamodb table the keySchema requires capital attribute keys currently (https://github.com/pulumi/pulumi-aws-native/issues/728)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
fixed with #728
