### ISSUE TITLE
Documented `getPartition` function not found error

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws-native#742]
### What happened?

According to the API documentation, the aws-native package has the `getPartition` function (see https://www.pulumi.com/registry/packages/aws-native/api-docs/getpartition/), just like the classic aws package. However, when you call the function you receive an error that the function is unknown.

### Steps to reproduce

```
import * as aws from "@pulumi/aws-native";

const partition = aws.getPartition();
```

### Expected Behavior

The actual partition to be returned, like within the aws-classic package

### Actual Behavior

``` Error: invocation of aws-native:index:getPartition returned an error: unknown function 'aws-native:index:getPartition'```

### Output of `pulumi about`

```
Dependencies:
NAME                VERSION
@pulumi/aws-native  0.44.0
@pulumi/pulumi      3.49.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
This should be fixed in the next release. See: https://github.com/pulumi/pulumi-aws-native/pull/746
