### ISSUE TITLE
[schema-generation] Strage type resolution on schema generation

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi-aws-native#777]
### What happened?

AWS CloudFormation Metric Stream property types were changed from:
```json
    "CreationDate" : {
      "oneOf" : [ {
        "format" : "date-time"
      }, {
        "format" : "timestamp"
      } ],
      "description" : "The date of creation of the metric stream.",
      "type" : "string"
    },
```

to:
```json
    "CreationDate" : {
      "description" : "The date of creation of the metric stream.",
      "type" : "string",
      "anyOf" : [ {
        "format" : "date-time"
      }, {
        "format" : "timestamp"
      } ]
```

Which resulted in an output schema type of:
```json
                "creationDate": {
                    "oneOf": [
                        {
                            "$ref": "pulumi.json#/Any"
                        },
                        {
                            "$ref": "pulumi.json#/Any"
                        }
                    ],
                    "description": "The date of creation of the metric stream."
                },
```

### Steps to reproduce

Define a schema object with a "oneOf" key with multiple format specifications.

### Expected Behavior

Expected behavior would be a schema object like this:
```json
                "creationDate": {
                    "type": "string",
                    "description": "The date of creation of the metric stream."
                },
```
or:
```json
                "creationDate": {
                    "type":  { "$ref": "pulumi.json#/Any" },
                    "description": "The date of creation of the metric stream."
                },
```

### Actual Behavior

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/4128006/212932111-d4cc5773-9673-47c1-a93d-8019ba7a7fbe.png">

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
It looks like our implementation of `anyOf` needs a revise. If I read this correctly, then

```
"type" : "string",
      "anyOf" : [ {
        "format" : "date-time"
      }, {
        "format" : "timestamp"
      }
```

means the

1. The type is `string`.
2. Format can be either `date-time`, `timestamp`, or both at the same time.

Instead, our current implementation ignores `string` entirely and parses the other two as Any.

Let's

A. Find the actual spec of `anyOf` in CloudFormation.
B. Review a few usage examples in actual CF schemas and make sure we understand all of them.
C. Adjust the implementation to support them correctly.

**Comment by mjeffryes** [comment]
Amusingly, there's [an issue](https://github.com/aws-cloudformation/cloudformation-resource-schema/issues/94) in [aws-cloudformation/cloudformation-resource-schema](https://github.com/aws-cloudformation/cloudformation-resource-schema) acknowledging that they they've adopted some undocumented behavior for `anyOf`, `allOf` and `oneOf`. However, it looks like [this is the base spec](https://json-schema.org/draft/2020-12/json-schema-core.html#section-10.2.1.2) it's based off of. 

In this specific instance, it looks like the intent of the schema is to specify a property with type `string` formatted as either `date-time` or `timestamp`. (I assume the switch from `oneOf` to `anyOf` was motivated by some strings where both formats match which causes `oneOf` to reject.)

There are a few other uses of `anyOf` in the CF schemas though which I'll spot-check for other misbehavior.

**Comment by mjeffryes** [comment]
another useful reference: https://json-schema.org/understanding-json-schema/reference/combining.html

I think the key idea is that we need to expand the values from the containing schema as default values into each of the arms of the `anyOf` in order to correctly handle factored schemas.
