### ISSUE TITLE
How to link InternetGateway to a VPC?

### ISSUE THREAD

**Issue by a-vivona** [pulumi/pulumi-aws-native#782]
In the documentation : https://www.pulumi.com/registry/packages/aws-native/api-docs/ec2/internetgateway/
I don't see how to link the internetGateway to a VPC.
There is no input corresponding to the VPC ID.

However, in the EgressOnlyInternetGateway, there is an input for the VPC.

Could you please give an example?

**Comment by squaremo** [comment]
I see the problem: the AWS API excpects you to create the InternetGateway then attach it to the VPC (https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html#Add_IGW_Attach_Gateway). AWS (classic) provider has AttachInternetGateway (https://www.pulumi.com/registry/packages/aws/api-docs/ec2/internetgatewayattachment/) for this purpose, but AWS native doesn't appear to have an equivalent.

**Comment by Wattabak** [comment]
Hi, bumping this since I still don't see a way to do this with the native provider. Classic also allows to just pass vpc_id to the InternetGateway [constructor](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/internetgateway/), but this argument is missing in the native [constructor](https://www.pulumi.com/registry/packages/aws-native/api-docs/ec2/internetgateway/).

**Comment by mjeffryes** [comment]
Unfortunately we don't support the [AwsVpcConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html) resource in aws-native because it is not present in the AWS CloudControl APIs.

**Comment by Wattabak** [comment]
Thank you for clarifying this, so strange that there is [TransitGatewayAttachment](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayvpcattachment.html) resource but no InternetGatewayAttachment in cloudcontrol API. Will keep this in mind, and use classic in the meantime to create the attachment resource

**Comment by vincentinttsh** [comment]
Hi,
I found that AWS have start support InternetGatewayAttachment in cloudcontrol API

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc-gateway-attachment.html

**Comment by mjeffryes** [comment]
@vincentinttsh
The [AwsVpcConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html) resource is in cloud formation, but it is not yet in the CloudControl APIs that aws-native uses. (So we can see the schema for this resource, but we don't have any API's we can call to create it!)

**Comment by ponceps** [comment]
Hi @vincentinttsh,
You can attach the internet gateway to the VPC as follows.

```
aws_native.ec2.VpcGatewayAttachment("main",
    internet_gateway_id=internet_gateway.id,
    vpc_id=vpc.vpc_id)
```

**Comment by ixti** [comment]
Is there a way to import VpcGatewayAttachment?
