### ISSUE TITLE
rds.DBCluster members have non-idiomatic names

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-aws-native#850]
### What happened?

The names of inputs for rds.DBCluster probably need to be aliased to more idiomatic names: https://www.pulumi.com/registry/packages/aws-native/api-docs/rds/dbcluster/

In TS, we have e.g. [dBClusterIdentifier](https://www.pulumi.com/registry/packages/aws-native/api-docs/rds/dbcluster/#dbclusteridentifier_nodejs) (should probably be `dbClusterIdentifier`).

In Python, we have `d_b_cluster_identifier`. That's definitely wrong.

### Expected Behavior

n/a

### Steps to reproduce

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
This issue looks like an instance of https://github.com/pulumi/pulumi-aws-native/issues/650

**Comment by mjeffryes** [comment]
resolved by #999
