### ISSUE TITLE
unrecognized resource type (Read): aws-native:ses:EmailIdentity

### ISSUE THREAD

**Issue by Fydon** [pulumi/pulumi-aws-native#852]
### What happened?

I tried to create an instance of [EmailIdentity](https://github.com/pulumi/pulumi-aws-native/blob/master/sdk/nodejs/ses/emailIdentity.ts), but received the following error when running `pulumi preview`: 
```
error: Preview failed: unrecognized resource type (Read): aws-native:ses:EmailIdentity
error: preview failed
```

### Expected Behavior

Create an [EmailIdentity](https://www.pulumi.com/registry/packages/aws-native/api-docs/ses/emailidentity/)

### Steps to reproduce

1. Create an EmailIdentity
2. Run `pulumi preview`

### Output of `pulumi about`

```
CLI
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.33.0
aws-native  0.55.0
nodejs      unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v16.15.0'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/foo
User           foo
Organizations  foo

Pulumi locates its logs in C:\Users\foo\AppData\Local\Temp by default
warning: Failed to get information about the Pulumi program's dependencies: found \pulumi\package-lock.json but not npm: unable to find program: npm.exe
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@Fydon Thanks for reporting this issue. To better assist, would you also be able to provide a code sample for us to see your configuration? Thanks!

**Comment by Fydon** [comment]
Sure, although I would expect any instance to not work.

```
import * as awsNative from '@pulumi/aws-native';

export const foo = new awsNative.ses.EmailIdentity(
  'fooConfiguration',
  {
    configurationSetAttributes: {
      configurationSetName: 'bar',
    },
    emailIdentity: 'foo@example.com',
    dkimAttributes: {
      signingEnabled: true,
    },
    feedbackAttributes: {
      emailForwardingEnabled: true,
    },
  }
);
```

**Comment by Fydon** [comment]
Sorry I tried this again and worked out the problem. As I am mixing AWS Classic and Native libraries, I was using an AWS Classic Provider with the AWS Native work.
