### ISSUE TITLE
Dynamodb table with ttl specification cannot update any property without error

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws-native#858]
### What happened?

If you create a dynamodb table with timeToLiveSpecification set, any update you try to push _after_ creating the table will result into an error.

The error _might_ be related to #728, where errors occurred because `AttributeName` (with capital) and `attributeName` were mixed up. This problem is fixed on the `keySchema`, but seems to live on within the `timeToLiveSpecification`.

Update: I found out that a similar bug was reported earlier by me as well (#730) where `timeToLiveSpecification` is required when updating a dynamodb table, so presumably a fix for this ticket will close both tickets.

### Expected Behavior

That updates to dynamodb table with timeToLiveSpecifications are processed.

### Steps to reproduce

Create a dynamodb like:

```
new aws.dynamodb.Table("dynamodb-table", {
  attributeDefinitions: [
    {
      attributeName: "Pk",
      attributeType: "S",
    },
    {
      attributeName: "Sk",
      attributeType: "S",
    }
  ],
  keySchema: [
    {
      attributeName: "Pk",
      keyType: "HASH",
    },
    {
      attributeName: "Sk",
      keyType: "RANGE",
    },
  ],
  tableName: "TEST_TABLE_NAME",
  billingMode: "PAY_PER_REQUEST",
  timeToLiveSpecification: {
    attributeName: "ttl",
    enabled: false,
  }
});
```

After creation, add the config lines: 
```
  streamSpecification: {
    streamViewType: "KEYS_ONLY"
  },
```

Now try to update the stack and you will get the error:

```
 aws-native:dynamodb:Table (dynamodb-table):
    error: operation error CloudControl: UpdateResource, https response error StatusCode: 400, RequestID: XXXX, api error ValidationException: Model validation failed (#/TimeToLiveSpecification: required key [AttributeName] not found)
```

### Output of `pulumi about`

```
Dependencies:
NAME                VERSION
@pulumi/aws-native  0.56.0
@pulumi/pulumi      3.61.0
@pulumi/random      4.12.1
```

### Additional context

I hope this issue could be resolved within a short time window as it's blocking for any serious dynamodb deployment.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hi @Jimmy89 - thank you for opening this issue! It looks like the linked fix for `KeySchema` didn't quite hit all of our cases - in this instance, `TimeToLiveSpecification` is not a `oneOf` attribute in the upstream schema, so we never hit the new conversion logic for this key. I'm not entirely sure what the correct fix is here beyond special-casing this attribute (which I'd prefer to avoid), but we'll give this a deeper look and try to get a resolution out to you as soon as we can. Thank you!

**Comment by Jimmy89** [comment]
@kpitzen This bug is quite annoying as it prevents us from updating the dynamodb tables we created. Is there any indication when this bug will be fixed?

**Comment by kpitzen** [comment]
Hi @Jimmy89 - thank you for reaching out again. We're currently making plans for the next few months worth of work, so I will be sure this makes it onto our roadmap as early into that process as possible.

**Comment by Jimmy89** [comment]
It seems my state was corrupted based on the previous reported bug, which creates this behavior. Thank you for testing and sorry for wasting your time, it seems to work fine after correcting the state.
