### ISSUE TITLE
Pulumi CLI support for AWS sso-session

### ISSUE THREAD

**Issue by OdmBkv** [pulumi/pulumi-aws-native#859]
## Pulumi cli when using AWS Native packages looks for the `sso_region, sso_start_url` in the aws config and unable to find them under the [sso_session xxx] portion.

This appears to mirror the issue raised in issue [2271 support sso-session](https://github.com/pulumi/pulumi-aws/issues/2272)

Please provide an update on fix or method to resolve without changing the sso_session as in workaround below.
tried without success things like
  - `pulumi config set aws-native:profile <my_profile_with_sso_session>`
work around (**not ideal**) but WORKS
  - reconfigure your config for aws profiles moving all the sso_stuff under [profile] and remove the [sso_session xxxx] part.

## SSO Error from `pulumi preview` with correct aws config
![Pulumi_CLI_SSO_Error](https://user-images.githubusercontent.com/107581372/229946151-f9659571-30fa-41c9-862c-c036d97e4c26.png)

## Reconfigured aws config
![Pulumi_CLI_SSO_Workaround](https://user-images.githubusercontent.com/107581372/229946452-3b2e5479-9e97-4f02-9f89-5d6b6ca02244.png)

**Comment by kpitzen** [comment]
Hi @OdmBkv - thank you for raising this for us. I'm glad you were able to find a workaround, but I agree there's room for improvement with the SSO experience here. We'll get this slated for work as soon as we can. Thanks again!

**Comment by OdmBkv** [comment]
@kpitzen I just updated the packages in one of my repo stacks for pulumi, pulumi-aws, and pulumi-aws-native to test the aws sso part.

After the update of pulumi-aws-native from 0.57.0 to 0.68.0 `pulumi preview` on the stack worked.
My total changes
aws-cli --version = 2.13
python 3.9.16
packages:
- pulumi 3.62.0 -> 3.74.0
    - test `pulumi preview` after **no change** on error
- pulumi-aws 5.35.0 -> 5.41.0 **no change**
    - test `pulumi preview` after **no change** on error
- pulumi-aws-native 0.57.0 -> 0.68.0
    - test `pulumi preview` after **worked**

So now my aws-cli can leverage all the profiles for my SSO login and pulumi, as I configured, uses the default correctly.

**Comment by JonCholas** [comment]
any plans to have this soon? it seems it he last step to have all of it working:
* pulumi cli now supports it 
* aws-classic now supports it
* pulumi credentials provider now supports it
* pulumi credentials with eks encryption now supports it

now is turn to aws-native to finally support it. I'm in the last version and still getting the error
```
Successfully installed pulumi-aws-native-0.96.0

Diagnostics:
  aws-native:chatbot:SlackChannelConfiguration (slack-chatbot):
    error: could not load AWS config: profile "<edited>" is configured to use SSO but is missing required configuration: sso_region, sso_start_url

```

**Comment by JonCholas** [comment]
Another ping on this, the aws-native is still the only blocker to adopt short-lived tokens for aws sso

**Comment by flostadler** [comment]
Hey @JonCholas, pulumi-aws-native should support AWS `sso-session`. I just tried verified this with the current (v1.0.0) version of the provider.

Please update to the latest version. If it's still not working run `pulumi about` in the directory of your pulumi program and attach it here so I can have a deeper look.

**Comment by JonCholas** [comment]
hey @flostadler it still doesn't work for me on version 1.0.0

Error

```
pulumi up
Previewing update (prod):
     Type                                             Name                     Plan     Info
     pulumi:pulumi:Stack                              aws-<redacted>-prod           2 warnings; 2 messages
     └─ aws-native:chatbot:SlackChannelConfiguration  <redacted>-slack-chatbot              1 error

Diagnostics:
  aws-native:chatbot:SlackChannelConfiguration (<redacted>-slack-chatbot):
    error: could not load AWS config: profile "<redacted>" is configured to use SSO but is missing required configuration: sso_region, sso_start_url
```

pulumi about
```
CLI
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  aws           6.54.0
resource  aws-native    1.0.0
resource  azure-native  2.42.1
resource  command       0.11.1
resource  gcp           6.67.0
resource  keycloak      5.3.2
resource  kubernetes    4.12.0
language  python        3.134.1
resource  random        4.15.1
resource  spacelift     0.0.0
resource  tls           4.11.1

Host
OS       darwin
Version  15.0
Arch     arm64

This project is written in python: executable='/Users/$USER/work/infra/venv/bin/python' version='3.11.10'

Current Stack: organization/<redacted>/prod

TYPE
<stripped urns for non native provider>
pulumi:providers:aws-native                                                                 urn:pulumi:prod::aws-<redacted>::pulumi:providers:aws-native::aws-native
aws-native:chatbot:SlackChannelConfiguration                                                urn:pulumi:prod::aws-<redacted>::neara:aws:SlackChatbot$aws-native:chatbot:SlackChannelConfiguration::<redacted>-slack-chatbot


Found no pending operations associated with prod

Backend
Name           <redacted>.local
URL            s3://<redacted>/stacks?awssdk=v2&region=ap-southeast-2&profile=pulumi-resources
User          <redacted>
Organizations
Token type     personal

Dependencies:
NAME                        VERSION
aws2-wrap                   1.4.0
black                       23.12.1
codeowners                  0.7.0
colorama                    0.4.6
docutils                    0.16
ephemeral-subenvs-operator  0.1.0
flake8                      6.1.0
isort                       5.13.2
Jinja2                      3.1.4
k8s-stacks                  0.1.0
pip                         24.2
pulumi_aws                  6.54.0
pulumi_aws_native           1.0.0
pulumi_azure_native         2.42.1
pulumi_command              0.11.1
pulumi-gcp                  6.67.0
pulumi_keycloak             5.3.2
pulumi_kubernetes           4.12.0
pulumi_random               4.15.1
pulumi_spacelift            0.0.0
pulumi-tls                  4.11.1
pyright                     1.1.364
pytest                      7.4.4
setuptools                  69.5.1
simple-term-menu            1.6.4
wheel                       0.43.0

Pulumi locates its logs in /var/folders/wq/j5hyjh_s25q0bvtvpvds99fm0000gn/T/ by default
```

**Comment by flostadler** [comment]
This is odd, the same setup with the same resource works for me:

~/.aws/config
```
[profile <Profile_NAME>]
sso_session = pulumi
sso_account_id = <REDACTED>
sso_role_name = AdministratorAccess
region = eu-west-1
[sso-session pulumi]
sso_start_url = <REDACTED>
sso_region = us-west-2
sso_registration_scopes = sso:account:access
```

Pulumi program
```python3
bucket = s3.Bucket('my-bucket')

role = iam.Role('my-role', assume_role_policy_document='{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"chatbot.amazonaws.com"},"Action":"sts:AssumeRole"}]}')

slack = chatbot.SlackChannelConfiguration('slack', iam_role_arn=role.arn, slack_workspace_id='T01B7LJQD9K', slack_channel_id='C01B7LJQD9K')
```

@JonCholas can you run `pulumi stack export --file stack.json` and check whether the resource (identified by its URN) is using the correct provider and whether the provider is correctly configured (correct profile, version, etc.). Ideally add the the json snippets for the resource and provider here.
I'd also recommend to create a separate pulumi project with minimal configuration to reproduce this. That way we can narrow the possible issues down.

**Comment by JonCholas** [comment]
@flostadler I did it and the version of the provided is the previous one, but that makes sense cause the export would have the state of the last good run and not the new version...

Could it be that I need to run `pulumi up --skip-preview` cause the preview is run with the old version and once upped it will store the right version?

**Comment by flostadler** [comment]
@JonCholas Yes that can be the case! You could either try running `pulumi up` without the `sso-session` settings or with skipping the preview. Once the provider is updated it should all work.

**Comment by flostadler** [comment]
Given that we haven't heard back, we're closing the issue for now. If you run into issues with using `sso-session` please open a new issue
