### ISSUE TITLE
Add option to enable AWS HTTP-level debug logs

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-aws-native#877]
The AWS SDK for Go has HTTP-level debug logs that are very helpful in debugging programs that are slow or appear to be stuck. Can we get an env var or config value that turns these logs on within the provider so I can see the output when I run a pulumi program? 

```
c := aws.NewConfig()
c.LogLevel = aws.LogLevel(aws.LogDebugWithHTTPBody)
sess, err := session.NewSession(c)
```

**Comment by kpitzen** [comment]
We currently implement this within the provider itself by passing `-v` options to the pulumi cli, along with `--logflow`, which propagates those options down to plugins.  In this case, running: `pulumi -v 11 --logflow up` will show only the HTTP requests and responses with AWS, and should achieve what's being requested here.
