### ISSUE TITLE
Schema discovery should remove existing files to avoid preserving removed resources

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-aws-native#901]
`make discovery` doesn't clean `aws-cloudformation-schema` before downloading the new schema. This could lead to JSON files   being used that were removed upstream.

**Comment by kpitzen** [comment]
This is a good catch - are we concerned with breaking changes that may arise from this? Do we need a way to manually curate what's removed from the resulting schema when it's removed upstream? What would a successful design look like here?
