### ISSUE TITLE
`sso_session` in AWS config doesn't work

### ISSUE THREAD

**Issue by richard-viney** [pulumi/pulumi-aws-native#954]
### What happened?

The following example config in `.aws/config` works with `@pulumi/aws` but does not work with `@pulumi/aws-native`.

```
[sso-session foo]
sso_start_url = https://REDACTED.awsapps.com/start#
sso_region = REDACTED
sso_registration_scopes = sso:account:access

[profile test]
sso_session = foo
sso_account_id = REDACTED
sso_role_name = REDACTED
region = REDACTED
output = json
```

The error is:

`could not load AWS config: profile "test" is configured to use SSO but is missing required configuration: sso_region, sso_start_url`

### Expected Behavior

The `sso_session` in the config file should be recognised, but it is not.

### Steps to reproduce

See above. The following issue looks very similar and suggests that a dependency upgrade may fix the problem:

https://github.com/hashicorp/terraform-provider-aws/issues/28263

### Output of `pulumi about`

CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v16.20.1'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Thanks for the research @richard-viney 

I've opened a PR to pull in these upgrades: #957
