### ISSUE TITLE
EKS Cluster updates fail with createOnlyProperties on Security Groups 

### ISSUE THREAD

**Issue by cmich3625** [pulumi/pulumi-aws-native#971]
### What happened?

When trying to pulumi up on an existing cluster in the stack it fails with the following error:
 aws-native:eks:Cluster (cluster):
    error: operation error CloudControl: UpdateResource, https response error StatusCode: 400, , NotUpdatableException: Invalid patch update: createOnlyProperties [/properties/ResourcesVpcConfig/SecurityGroupIds] cannot be updated

In our code not only are we not setting any secuirtyGroupIds we are telling it to ignore changes on the setting with the below line,
pulumi.IgnoreChanges([]string{"resourcesVpcConfig.securityGroupIds"}))

### Expected Behavior

Expect the cluster to update without the above error

### Steps to reproduce

Build a cluster with the aws-native eks package,
Make a change in the ClusterArgs.ResourcesVpcConfig
pulumi up 

### Output of `pulumi about`

pulumi about         
pp=pulumi
CLI          
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.18.0
aws-native  0.67.0
go          unknown
kubernetes  3.25.0
random      4.10.0
tls         4.8.0

Host     
OS       debian
Version  bookworm/sid
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.20 linux/amd64'

Backend        
Name           pop-os

Dependencies:
NAME                                              VERSION
github.com/pulumi/pulumi-aws/sdk/v5               5.18.0
github.com/pulumi/pulumi/sdk/v3                   3.63.0
github.com/pulumi/pulumi-tls/sdk/v4               4.8.0
github.com/pulumi/pulumi/pkg/v3                   3.63.0
github.com/stretchr/testify                       1.8.2
github.com/pulumi/pulumi-aws-native/sdk           0.67.0
github.com/pulumi/pulumi-kubernetes/sdk/v3        3.25.0
github.com/pulumi/pulumi-random/sdk/v4            4.10.0
gopkg.in/yaml.v3                                  3.0.1

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
similar to #941

**Comment by mjeffryes** [comment]
should be fixed by https://github.com/pulumi/pulumi-aws-native/pull/1053
