### ISSUE TITLE
Wrong filename for release

### ISSUE THREAD

**Issue by contactgus** [pulumi/pulumi-aws-native#997]
### What happened?

Plugin install fails with a 404 error because I think the filename in the pulumi package repo is incorrect

### Expected Behavior

Plugin should install correctly

### Steps to reproduce

Run the following:
```
pulumi plugin install resource pulumi_aws_native
```
It returns:
```
error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-pulumi_aws_native/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

### Output of `pulumi about`

```
CLI
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Host
OS       rocky
Version  9.2
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/*******
User           *****
Organizations  *******

Pulumi locates its logs in /tmp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /root). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from /root). If you have not created a project yet, use `pulumi new` to do so: no project file found
```

### Additional context

If you wget the pulumi package server with the filename it expects it fails:
```
wget https://get.pulumi.com/releases/plugins/pulumi-resource-pulumi_aws_native-v0.69.0-linux-amd64.tar.gz
```

But if you use the filename that comes from the github release it works:
```
wget https://get.pulumi.com/releases/plugins/pulumi-resource-aws-native-v0.69.0-linux-amd64.tar.gz
```

So Pulumi plugin installer expects: `pulumi-resource-pulumi_aws_native-v0.69.0-linux-amd64.tar.gz`
But the package filename is the same as the github release: `pulumi-resource-aws-native-v0.69.0-linux-amd64.tar.gz`

Workaround: Download the release from github and use:
```
pulumi plugin install resource pulumi_aws_native v0.69.0  --file ./pulumi-resource-aws-native-v0.69.0-linux-amd64.tar.gz
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
The correct plugin installation command should look like this:

```
pulumi plugin install resource aws-native
```

What was the workflow that led you to run `pulumi plugin install resource pulumi_aws_native`?

**Comment by contactgus** [comment]
Thanks, I probably mixed up the python package name with this pulumi package name. Sorry for wasting your time!

**Comment by mikhailshilkov** [comment]
No worries! It sounds like I can close the issue - but feel free to open a new open if there is a problem.
